### ISSUE TITLE
2fa_state_changed error after enter refresh token

### ISSUE THREAD

**Issue by marcswiss** [iMicknl/ha-nest-protect#1]
Just after enter refresh token i got follow error in logs...
On UI i just got "Unexpected error"

```
Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:139
Integration: nest_protect (documentation)
First occurred: 21:01:33 (1 occurrences)
Last logged: 21:01:33


'2fa_state_changed'
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 40, in async_step_user
    refresh_token = await self.async_validate_input(user_input)
  File "/config/custom_components/nest_protect/config_flow.py", line 28, in async_validate_input
    await client.authenticate(
  File "/config/custom_components/nest_protect/pynest/client.py", line 139, in authenticate
    nest_response["_2fa_state_changed"] = nest_response.pop("2fa_state_changed")
KeyError: '2fa_state_changed'
```

**Comment by iMicknl** [comment]
Thanks! Do you perhaps have no 2 factor authentication on your Google Account?

Could you give https://github.com/iMicknl/ha-nest-protect/archive/refs/heads/fix/1.zip a try? Unzip `custom_components/nest_protect` and overwrite your current `nest_protect` folder.

**Comment by geert36** [comment]
I had the same issue. The fix does solve the problem!

**Comment by iMicknl** [comment]
Thanks @geert36! Not sure where this key is froming come, since I have it present in my response. 0.1.1 has this fix. 

Do all other sensors show up / work? (with current limitations taken into account).

**Comment by geert36** [comment]
Most of the sensors does show up. I only see some difference here (compared to your post [here](https://community.home-assistant.io/t/support-for-nest-protect/310084/20)).
![image](https://user-images.githubusercontent.com/77209691/149638754-21e348d0-25bb-417b-9c33-76fc9856591b.png)

**Comment by iMicknl** [comment]
Thanks! @geert36 do the normal sensor (CO / Smoke / Heat / Occupancy) work as well? And is your device model Topaz-2.33 as well?

I wonder why you don't have the "Replace By" sensor.

**Comment by geert36** [comment]
The normal sensors work as well!
Sorry, I forget to mention, I have a battery powered Nest (Topaz-2.9).

**Comment by marcswiss** [comment]
Sorry, for my slow response. i had originally 2fa disabled on my house account, but after enabling was still not work. Proberly google cache something..

However with newst version /patch is now working. I found all my 6 nest protect ;)
Thx @geert36  and @iMicknl 

i have Topaz-2.7 and 2.9

![image](https://user-images.githubusercontent.com/51174465/149639436-7b8159e5-6b25-43b1-8bcc-9284566152ea.png)

**Comment by iMicknl** [comment]
Great, thanks! At least the basics work for now 😃. You will see some more updates in the coming weeks.
