### ISSUE TITLE
Options is available as a standard property of SelectEntityDescription

### ISSUE THREAD

**Issue by epenet** [iMicknl/ha-nest-protect#106]
### The problem

As of Home Assistant Core 2022.11, options is available as a standard property of SelectEntityDescription.
This may cause issues in custom components if a custom options property was previously implemented.

Please adjust the custom component by either dropping or renaming the custom options property.

See https://github.com/home-assistant/core/pull/78882

**Comment by iMicknl** [comment]
Thanks @epenet, I saw your PR passing by and will fix it in the custom component. Good improvement to core.

**Comment by epenet** [comment]
Please be aware that this will only be available from 2022.11 release.
If you wish to be compatible with both 2022.10 and 2022.11 you may need to rename the options property.

**Comment by fishbone-git** [comment]
I believe this is now causing a problem in the 2022.11b0
2022-10-27 18:49:48.655 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.nest_protect.select
2022-10-27 18:49:48.662 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).

I see it is merged, but is it ready for release in good time?

**Comment by fishbone-git** [comment]
easy fix, I just removed line 18 of select.py

**Comment by iMicknl** [comment]
@fishbone-git I will release a new version soon. I planned to do this just before the release, however it makes sense to do this earlier in case you want to try the beta.

**Comment by Anto79-ops** [comment]
hey, awesome thanks for the fix!

How long does it take for HACS to know an update for this integration is available? simply "updating information" does not show 0.3.9 version. thanks

**Comment by iMicknl** [comment]
@Anto79-ops do you run 2022.11? This update is only available for users running 2022.11, since it will break 2022.10 functionality.

**Comment by Anto79-ops** [comment]
Im running 2022.11b4 now

**Comment by Anto79-ops** [comment]
ok, all good. it was redownload that solved the issue. cheers!
