### ISSUE TITLE
Platform not found?

### ISSUE THREAD

**Issue by atv2016** [iMicknl/ha-nest-protect#118]
### The problem

I am getting this in the logs after a restart now:
Logger: homeassistant.setup
Source: setup.py:320 
First occurred: 14:23:10 (1 occurrences) 
Last logged: 14:23:10

Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).

### What version of this integration (ha-nest-protect) has the issue?

can't find this info, but latest

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest

### Device / Model

battery

### Diagnostics information

Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

Topaz-2.9
by Google
Firmware: 3.4.1rc1

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```
none
</details>

### Additional information

none

**Comment by iMicknl** [comment]
Please update to the latest version of ha-nest-protect, you are probably not running the latest version.

**Comment by atv2016** [comment]
yeah i saw an update, this is resolved now. thanks!
