### ISSUE TITLE
Can't access the integration

### ISSUE THREAD

**Issue by Snomisleor** [iMicknl/ha-nest-protect#119]
### The problem

After Downloading the repository, (checked in file explorer) accessing the integrations fails instantly stating:

Fout
Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

### What version of this integration (ha-nest-protect) has the issue?

0.3.10

### What version of Home Assistant Core has the issue?

core- 2022.11.2

### Device / Model

N/A

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
@Snomisleor what was the solution? I think you didn't install it in the right way, but it would be great if you can share what solved it for you.
