### ISSUE TITLE
Failed to connect error while using cookies

### ISSUE THREAD

**Issue by danieldevos90** [iMicknl/ha-nest-protect#122]
### The problem

Can you guys help me with this error? I logged in on home.nest.com and followed the guide after I got the other issue on logging in.

```
Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:219
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 8:14:31 PM (3 occurrences)
Last logged: 8:16:50 PM

400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"27334ad0-f0f8-4467-9c56-0e4bd11aa022"}. Please create an issue on GitHub.
400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"fc7af587-a67b-4d19-ba4c-7b9c2e71975b"}. Please create an issue on GitHub.
400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"fadec021-38cf-432e-ad5d-da81ce319b7c"}. Please create an issue on GitHub.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 215, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 104, in async_step_account_link
    [issue_token, cookies] = await self.async_validate_input(user_input)
  File "/config/custom_components/nest_protect/config_flow.py", line 62, in async_validate_input
    await client.authenticate(
  File "/config/custom_components/nest_protect/pynest/client.py", line 219, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"27334ad0-f0f8-4467-9c56-0e4bd11aa022"}. Please create an issue on GitHub.`
```

### What version of this integration (ha-nest-protect) has the issue?

0.3.10

### What version of Home Assistant Core has the issue?

2022.11.3

### Device / Model

Raspberry Pi

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Are you using #121?

**Comment by danieldevos90** [comment]
I use this package: 5dd36d1

And my issueToken looks like;
https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token id_token&login_hint=AJDLj6LQu....

and cookie like;
__Secure-3PSID=QwjE_wMpEk7E0L2Uq13vknwx7AQ-Oj499QlOAnqZIACxXDQLD5jJ9rt82PfgUmUjYiMF8Q.; __Secure-3PAPISID=VQpD3LYfCAbxLswI/ALTk4EDLUM84AmCD1; NID=511=dWV6MqCYXe7x3WtdIgWYuAiCrmNbY0UPHWz33mk2Kob---BaSlCtaOxuMjcYmK03GDRStPJqX-.......

`Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:219
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 4:47:40 PM (1 occurrences)
Last logged: 4:47:40 PM

400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"d1e3e443-9752-4d83-9bf3-746ffee6cd9f"}. Please create an issue on GitHub.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 215, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 104, in async_step_account_link
    [issue_token, cookies] = await self.async_validate_input(user_input)
  File "/config/custom_components/nest_protect/config_flow.py", line 62, in async_validate_input
    await client.authenticate(
  File "/config/custom_components/nest_protect/pynest/client.py", line 219, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"d1e3e443-9752-4d83-9bf3-746ffee6cd9f"}. Please create an issue on GitHub.`

**Comment by danieldevos90** [comment]
@iMicknl Do you maybe have any id? Missing user credentials?

**Comment by iMicknl** [comment]
I don't have time to look at this currently, and you are also not running my code. 😉

**Comment by x-luthor** [comment]
Hey There,

Thanks for this integration.  I got it working with some help last Friday but it seems to lock up (stop updating) after about 4-5 hours.   A re-boot fixes the issue.  This occurrs consistently for me and a friend running the same integration.

![Failure](https://user-images.githubusercontent.com/73357736/204548080-b8378c81-5782-43bc-889f-46c3895dfb0a.png)

Is anyone else experiencing this using the cookie authentication method?

**Comment by nicoinch** [comment]
I think this issue is already solved, can you try to reinstall the integration, please?

**Comment by SgtFoose** [comment]
I have the same issue. When I press "Save" I do get a 200 ok, no errors in Inspect?

Save send:

General:
Request URL: http://homeassistant.local:8123/api/config/config_entries/flow/2f4c94f8b98ee4977778a3390cf1f2bd
Request Method: POST
Status Code: 200 OK
Remote Address: [fe80::8c71:50dd:c572:6e87]:8123
Referrer Policy: same-origin

Response Headers:
Content-Encoding: deflate
Content-Length: 201
Content-Type: application/json
Date: Tue, 13 Dec 2022 10:41:32 GMT
Server: Python/3.10 aiohttp/3.8.1

Request Headers:
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en,nl;q=0.9,ru;q=0.8
authorization: Bearer eyJhbGciOiJIUz**blablablablabla**
Connection: keep-alive
Content-Length: 2036
Content-Type: application/json;charset=UTF-8
DNT: 1
HA-Frontend-Base: http://homeassistant.local:8123
Host: homeassistant.local:8123
Origin: http://homeassistant.local:8123
Referer: http://homeassistant.local:8123/config/integrations
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**Comment by nicoinch** [comment]
I also struggled identifying the update process, the API call to Nest can have huge response time with no update concerning the Nest Protect devices. I also thoughts there was update issues until smoke correctly triggered the alert. So to sum up my understanding of the API, it will only update Nest Protect entity if something has changed, otherwise, the API will respond (sometimes with huge delays) but with no information for Nest Protect so it seemed the update is not working, but it is.

Unfortunately, I do not have an Home Assistant instance anymore, so I won't be able to further progress on this integration. Sorry about that...
