### ISSUE TITLE
Unknown Exception popping up every 5 seconds

### ISSUE THREAD

**Issue by janusn** [iMicknl/ha-nest-protect#124]
### The problem

I have got an error popping up on the log every 5 seconds. The Nest Protect Devices and entities seem working fine though.

### What version of this integration (ha-nest-protect) has the issue?

0.3.10

### What version of Home Assistant Core has the issue?

core-2022.11.5

### Device / Model

Nest Protect (Topaz-2.9)

### Diagnostics information

[config_entry-nest_protect-d9d72164fb1de9ad1884f574ae28ec3c.json.txt](https://github.com/iMicknl/ha-nest-protect/files/10132916/config_entry-nest_protect-d9d72164fb1de9ad1884f574ae28ec3c.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```2022-12-01 05:28:37.479 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 173, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/config/custom_components/nest_protect/pynest/client.py", line 187, in authenticate
    nest_auth = NestAuthResponse(**result)
  File "<string>", line 4, in __init__
TypeError: NestAuthClaims.__init__() missing 4 required positional arguments: 'subject', 'expirationTime', 'policyId', and 'structureConstraint'
2022-12-01 05:33:37.682 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 173, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/config/custom_components/nest_protect/pynest/client.py", line 187, in authenticate
    nest_auth = NestAuthResponse(**result)
  File "<string>", line 4, in __init__
TypeError: NestAuthClaims.__init__() missing 4 required positional arguments: 'subject', 'expirationTime', 'policyId', and 'structureConstraint'
2022-12-01 05:38:37.819 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 173, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/config/custom_components/nest_protect/pynest/client.py", line 187, in authenticate
    nest_auth = NestAuthResponse(**result)
  File "<string>", line 4, in __init__
TypeError: NestAuthClaims.__init__() missing 4 required positional arguments: 'subject', 'expirationTime', 'policyId', and 'structureConstraint'
2022-12-01 05:43:37.958 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 173, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/config/custom_components/nest_protect/pynest/client.py", line 187, in authenticate
    nest_auth = NestAuthResponse(**result)
  File "<string>", line 4, in __init__
TypeError: NestAuthClaims.__init__() missing 4 required positional arguments: 'subject', 'expirationTime', 'policyId', and 'structureConstraint'
```

</details>

**Comment by iMicknl** [comment]
@Rustymage @janusn do both of you use the last released version, or the PR from @nicoinch with the new cookie method?

**Comment by iMicknl** [comment]
@Rustymage on the top I see the commit-id from https://github.com/iMicknl/ha-nest-protect/pull/121. You are running a test version (which you installed by hand 😉).

**Comment by Rustymage** [comment]
Me, no never!

Urm - clearly needs a little tweak if it's a test version ;) 

Anything from me to help/support logwise?

**Comment by janusn** [comment]
> @Rustymage @janusn do both of you use the last released version, or the PR from @nicoinch with the new cookie method?

I use the latest version with google access token. I am not sure how to know the version installed but I have installed through custom repository with the following URL:
`https://github.com/nicoinch/ha-nest-protect`

**Comment by nivek1612** [comment]
Seeing the same I think 

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:191 
Integration: Nest Protect (documentation, issues) 
First occurred: 01:39:59 (6 occurrences) 
Last logged: 07:53:57

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
  File "/config/custom_components/nest_protect/pynest/client.py", line 191, in authenticate
    "cookie": "G_ENABLED_IDPS=google; eu_cookie_accepted=1; viewer-volume=0.5; cztoken="
TypeError: can only concatenate str (not "NoneType") to str

**Comment by othorp** [comment]
Seeing the same issue reported by Rustymage and nivek1612 here.  Log message appears every 30mins but Nest Protect functionality is mostly working so seems to be a transient error.

**Comment by hmorkemo** [comment]
The same happens here. Functionality of the units (3) seems ok. The iPhone Nest app reports everything's ok.
Diagnostics file attached.
[config_entry-nest_protect-87172a1dcafae6a69f95023c5bdb62b0.json.txt](https://github.com/iMicknl/ha-nest-protect/files/10661963/config_entry-nest_protect-87172a1dcafae6a69f95023c5bdb62b0.json.txt)

**Comment by Morriz** [comment]
+1

Verified thrown by this custom component installed from this repo.

```
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
  File "/config/custom_components/nest_protect/pynest/client.py", line 191, in authenticate
    "cookie": "G_ENABLED_IDPS=google; eu_cookie_accepted=1; viewer-volume=0.5; cztoken="
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by B-double-U** [comment]
Same issue here. HA on latest version. Integration seems to work fine though...

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:191 
Integration: Nest Protect (documentation, issues) 
First occurred: March 25, 2023 at 18:18:28 (14 occurrences) 
Last logged: 10:12:47

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
  File "/config/custom_components/nest_protect/pynest/client.py", line 191, in authenticate
    "cookie": "G_ENABLED_IDPS=google; eu_cookie_accepted=1; viewer-volume=0.5; cztoken="
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Cruguah** [comment]
I've implemented a fix, please let me know if this works

**Comment by janusn** [comment]
> I've implemented a fix, please let me know if this works

How do I get the updated version?

**Comment by Cruguah** [comment]
Because the version number can't be updated, you need to reinstall the integration by manualy update the sourcecode of the integration. When using HACS you can do this by opening the nest integration and redownload the integration
![image](https://user-images.githubusercontent.com/14362766/229140602-3fad000e-1458-4bd9-950d-46042681d233.png)
Restart HA and you're using the latest code

**Comment by janusn** [comment]
Thanks for the tips.

I have updated and HA has been upped this morning by watchtower. The unknown exception still pops up around every 1.5 hours. Please consult the attached log.
[ha.log](https://github.com/iMicknl/ha-nest-protect/files/11129058/ha.log)

**Comment by Cruguah** [comment]
Hello Janus,

I've looked at your logfile, it almost feels like the credentials are not stored and can't be retrieved/used to call the google services.
Have you reinstalled the integration with new credentials?

Kind regards.

**Comment by janusn** [comment]
> Hello Janus,
> 
> I've looked at your logfile, it almost feels like the credentials are not stored and can't be retrieved/used to call the google services. Have you reinstalled the integration with new credentials?
> 
> Kind regards.

You are right. I didn't change the credentials after redownloaded the plugin.

In fact, I don't know how to change the credentials. Could you enlighten me?

Cheers.

**Comment by janusn** [comment]
Thank you very much for your help.

1. I have tried to redownload and restart HA again as suggested. But no configuration option was shown as illustrated below.
<img width="303" alt="Screen Shot 2023-04-06 at 3 47 15 pm" src="https://user-images.githubusercontent.com/21253783/230424517-4f5e193e-7384-4fc8-b6b9-1341e2b9231e.png">

2. I removed all the integration and deleted the HACS integration. Then I added the nest_protect integration again in HACS. One thing I noticed.  There were 2 nest protect repositories shown when I have entered "nest" in the search box. They are both showing exactly the same descriptions. And yours was the second one sorted by default "star" option. Too bad I didn't take a screencap at it. Could you add some indications to distinguish them for users?

3. I went ahead and authenticated as the readme said, with issue_token and cookies. One remark though. The intl translation has missed English as illustrated below.
<img width="600" alt="Screen Shot 2023-04-06 at 4 05 14 pm" src="https://user-images.githubusercontent.com/21253783/230426832-f4bcc6e0-ac72-4e17-ac04-3d66d5ed963b.png">

4. Finally I have got it up and running. No error related this issue has been shown so far. Finger crossed. However, issue #194 is still logged.

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
