### ISSUE TITLE
Occupancy not updated / triggered

### ISSUE THREAD

**Issue by GentleGiantSoftware** [iMicknl/ha-nest-protect#125]
### The problem

Occupancy is not updated / triggered. On the nest I see the white light coming on, so all is working fine. The occupancy value seems to be read correctly from the (powered) Nests when HA is started, but does not seem to change after that anymore. Sometimes the values are updated assuming this happens when other sensor values get updated, I hoped to use the occupancy as a direct trigger but seems not to be working. Nothing shows up in the logs, not even with debugging enabled (also not after a restart of HA). 

### What version of this integration (ha-nest-protect) has the issue?

0.3.10 (in Hacs) 0.3.8 (in logs)

### What version of Home Assistant Core has the issue?

2022.12.7

### Device / Model

Nest Protect (3 on power, 1 on battery)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by Tatey53** [comment]
I can confirm that I am seeing the same issue.  Like you, when HA is first started or restarted to the occupancy updates, and works and updates for a short time afterwards.  However at some point after circa 30 minutes, HA fails to update, and will remain at the same status until HA is restarted.  An example of the history log since the last HA restart is attached.  
![image](https://user-images.githubusercontent.com/113981314/212713845-7296b987-3336-4f87-823e-531ce2a4bf9c.png)

**Comment by iMicknl** [comment]
@Tatey53 can you share your log file and diagnostics file as well? Are you running the main branch or the cookie method?

**Comment by Tatey53** [comment]
Hi @iMicknl,

Thanks for getting back to me.  I am using the cookie method.  Logs are attached.  Reading them myself it would appear there is something it doesn't like.  Maybe someone else would be able to decipher the error.

[config_entry-nest_protect-ad8fbad14bcaeec16d5019457400c446.json.txt](https://github.com/iMicknl/ha-nest-protect/files/10446630/config_entry-nest_protect-ad8fbad14bcaeec16d5019457400c446.json.txt)
[home-assistant_2023-01-18T13-14-51.526Z.log](https://github.com/iMicknl/ha-nest-protect/files/10446631/home-assistant_2023-01-18T13-14-51.526Z.log)

**Comment by Tatey53** [comment]
To add to the above, I am using the cookie method

**Comment by B-double-U** [comment]
Same issue here, using the cookie method.
Reloading the integration solves it but is obviously not ideal...

**Comment by Cruguah** [comment]
I do see the sensor being updated in HA, but not because the sensor is triggering an update. The occupancy sensor is updated irregularly and is not reliable to use in HA

![image](https://user-images.githubusercontent.com/14362766/228373766-78013ff6-92df-4601-ba6b-52e23d35337c.png)

**Comment by iMicknl** [comment]
Can you all test the latest beta version, and let me know if you still face issues? I will be working on this integration again and good to understand the issues with the cookie method.

**Comment by B-double-U** [comment]
> Can you all test the latest beta version, and let me know if you still face issues? I will be working on this integration again and good to understand the issues with the cookie method.

I’ve installed v0.4.0b4 a few days ago and everything seems to work OK.

**Comment by cooltings** [comment]
Seems to be working on new beta

**Comment by Pixel-Gavin** [comment]
I'm on v0.4.0b4 (never been on any other) and the occupancy sensor is very ropey for me, almost always detecting somebody there.
The white light works as expected, and doesn't have any "ghost" triggers, but the API seems to be all over the place.
Today there is nobody in the house...

![image](https://github.com/iMicknl/ha-nest-protect/assets/10983396/5494eb44-80d7-4cac-b544-c0f080ea8cb1)

**Comment by cooltings** [comment]
Actually been a couple of days and it is getting stuck again:
<img width="548" alt="Screenshot 2023-12-22 at 17 01 19" src="https://github.com/iMicknl/ha-nest-protect/assets/104278596/bb673ef0-122d-4f6a-9d1e-aa7f7014c740">

**Comment by iMicknl** [comment]
@Pixel-Gavin please turn on debug mode and create a new issue for your 'ghost issues'. 

@cooltings I will work on creating better debug logging, but I have seen these issues as well when the connectivity is lost.

**Comment by Pixel-Gavin** [comment]
@iMicknl I will do that. I'm pretty convinced that it's not connectivity in my case as I can update the settings and see them updating in realtime on the Nest app.

**Comment by B-double-U** [comment]
Indeed now looking back after a couple of days the occupancy detections are way off.
In the previous version I was on, these worked fine. I think it was the b1 or b2.

**Comment by kahancock** [comment]
Following this. I'm also on b4 and have the same mix of wired and wireless with the exact same behavior as above.

**Comment by stormshaker** [comment]
Same for me - I'm on 0.4.0b4 (cookie method) and my occupancy sensor gets stuck after every couple of days. I can fix it by reloading the integration config in HA - no need to restart HA and no need to do anything in HACS.

**Comment by iMicknl** [comment]
Please try the latest version. If you face any issues, please open a new issue and add your latest logs :).
