### ISSUE TITLE
will fail in version 2023.3

### ISSUE THREAD

**Issue by neildsb** [iMicknl/ha-nest-protect#148]
### The problem

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 103: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

### What version of this integration (ha-nest-protect) has the issue?

latest

### What version of Home Assistant Core has the issue?

2023.3

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Already fixed in main branch, just not released yet.
