### ISSUE TITLE
Keep history

### ISSUE THREAD

**Issue by mfscorp** [iMicknl/ha-nest-protect#157]
### Description

Hi 
Is it possible to keep/retain the history of the nest protect ?
So smoke/co history?

Currently i only see the history that is also present in nest app.

### Device (optional)

Nest Protect (wireless)

**Comment by iMicknl** [comment]
What do you mean? Can you clarify your request a bit?

Your history is logged in Home Assistant and you can change the retention time of the recorder. (this is not related to this integration).

**Comment by mfscorp** [comment]
ah i see, my bad here no enhancement needed, the recorder configuration is were i need to be.
closing request
