### ISSUE TITLE
Warning Message in log regarding async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by paisore** [iMicknl/ha-nest-protect#165]
### The problem

When I reloaded HA today I found this warning message in the logs: 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 6:33:02 PM (1 occurrences)
Last logged: 6:33:02 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 126: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

Although the component seems to still work, I am thinking it may mean they will deprecate async_setup_platforms.

### What version of this integration (ha-nest-protect) has the issue?

0.4.0

### What version of Home Assistant Core has the issue?

2023.2.3

### Device / Model

Topaz-2.9 Wired

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Are you running the cookie version? You mention you run version 0.4.0, but we didn’t even release this one yet?

**Comment by paisore** [comment]
Hi, 

I got the version number from downloading the diagnostic from the integration. The resulting json show this entry:

    "nest_protect": {
      "version": "0.4.0",
      "requirements": []

I am running the cookie version has the token had seemed to be deprecated by google.

Thanks for everything and let me know if I can be of any assistance.

**Comment by iMicknl** [comment]
This is not the version that is merged in this repository. Best for now would be to move back to the cookie method version; hopefully we can merge the efforts soon.
