### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by trouble2** [iMicknl/ha-nest-protect#168]
### The problem

When click on the authorize your account link I get a message saying Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

2023.2.4

### Device / Model

nest battery

**Comment by iMicknl** [comment]
Duplicate of #105. (which I accidentally closed).

**Comment by deezid** [comment]
Same issue here

**Comment by alexr544** [comment]
Same issue here

**Comment by ajroads** [comment]
Hi, I have same issue - is this likely to get resolved?

**Comment by iMicknl** [comment]
See the linked issue. You will need the latest beta version.
