### ISSUE TITLE
Wrong Device Icon

### ISSUE THREAD

**Issue by weswitt** [iMicknl/ha-nest-protect#169]
### The problem

in the grand scheme of things this is minor, but on my system the device icon for all nest protect devices is the ubiquity network icon and not the google icon. is there a way to change the icon in a config file or your code?

### What version of this integration (ha-nest-protect) has the issue?

0.4.0

### What version of Home Assistant Core has the issue?

Supervisor 2023.02.dev1502

### Device / Model

Topaz-2.9

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
@weswitt not that I am aware of. Best would be to log this bug in the frontend repository on core. Both are linked to the same unique identifier (mac address) for a device, and apparently Ubiquity is the last one to set this? Doesn't seem like a way where we can override this.
