### ISSUE TITLE
Implement reauth flow (reconfigure) on USER_LOGGED_OUT

### ISSUE THREAD

**Issue by miczlo** [iMicknl/ha-nest-protect#170]
### The problem

So I'm getting Retrying setup: USER_LOGGED_OUT
I imagine this is due to the cookie going stale, but what is the correct way of handling this other than delete and recreate?
I would expect a Reconfigure option to go through the cookie setup again.

### What version of this integration (ha-nest-protect) has the issue?

1e62797

### What version of Home Assistant Core has the issue?

2023.2.5

### Home Assistant log

<details><summary>Logs</summary>
USER_LOGGED_OUT
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 77, in async_setup_entry
    auth = await client.get_access_token_from_cookies(issue_token, cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 159, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
</details>

### Additional information

It's been working fine for some time

**Comment by miczlo** [comment]
Looking at it it seems I'm using a fork actually

**Comment by iMicknl** [comment]
You are, however, we are trying to incorporate these changes in this integration.

@Cruguah, this would be something we need to tackle before we can release the cookie method. https://github.com/iMicknl/ha-nest-protect/pull/167

**Comment by Cruguah** [comment]
I've had the same issue after resetting the version number. Deleting the integration and recreating it solved the problem (work around). I had to redo the steps of the issue_token and cookies

**Comment by tbclark3** [comment]
I am consistently getting the user_logged_out error about an hour after I go through the cookie process.  I have deleted and recreated the integration numerous times, but it doesn't seem to make a difference.

**Comment by jonpetersathan** [comment]
> I am consistently getting the user_logged_out error about an hour after I go through the cookie process. I have deleted and recreated the integration numerous times, but it doesn't seem to make a difference.

Same here, it worked for almost a day, until I restarted my Home Assistant and know it fails. After checking the debug log when reloading the integration, I also get "USER_LOGGED_OUT".

**Comment by tbclark3** [comment]
Try using an incognito window instead of just clearing the cache.  After trying incognito mode, I am now staying logged in even over restarts of HA.  I wonder if the original instructions should have said "clear your cookies" instead of "clear your cache."

**Comment by jonpetersathan** [comment]
> Try using an incognito window instead of just clearing the cache. After trying incognito mode, I am now staying logged in even over restarts of HA. I wonder if the original instructions should have said "clear your cookies" instead of "clear your cache."

Will give it a shoot, thanks! Yeah, I have only cleared my cache... I also noticed, the cookie looks a bit different know, when trying through incognito mode.

**Comment by fromariz** [comment]
Any updates on this issue?
I'm using v0.4.0b4 with HA Core 2024.4.2 and every other week I have to do all the authorization process again.

**Comment by jonpetersathan** [comment]
@fromariz Did you try what @tbclark3 suggested? Doing the authorization process in an incognito window? For me this fixed it, running for a couple of months now without any issues.

I assume the token issued when doing this in an incognito has a longer lifetime. Probably because to some cookies, when using a normal browser window.

**Comment by fromariz** [comment]
I was trying from a Chrome Anonymous window and was not being able to even get it to authenticate.
I have tried no in an Edge instance where I had never logged in to Nest, got all the data and tried again.
Let's see for how long it will keep the session.
Thanks @jonpetersathan

**Comment by varyamereon** [comment]
I am having the same issue with USER_LOGGED_OUT. Where do we put the new issue_token/cookies? Or do we have to delete the integration and add it again? What happens to our existing entities when we do that?

**Comment by iMicknl** [comment]
Please update to v0.4.0b5 and let me know if this issue is still present.
