### ISSUE TITLE
OAuth out-of-band (OOB) flow depriciated

### ISSUE THREAD

**Issue by Zaleo80** [iMicknl/ha-nest-protect#192]
### The problem

Not sure if I am doing something wrong here or the integration is broken.
But after I try to authenticate my account I get this message:

```
Error 400: invalid_request

The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Details van verzoek: redirect_uri=urn:ietf:wg:oauth:2.0:oob
```

Refeuring me to this site : [Out-Of-Band (OOB) flow Migration Guide](https://community.home-assistant.io/t/support-for-nest-protect/310084)

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

Supervisor 2023.03.2 Operating System 9.5 Frontend-versie: 20230309.1 - latest

### Device / Model

Nest Protect (Battery)

### Home Assistant log

As the intergration did not start without a accesstoken I have no log's in HA.

**Comment by iMicknl** [comment]
See #105
