### ISSUE TITLE
[homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by janusn** [iMicknl/ha-nest-protect#194]
### The problem

HA complains in the logs whenever it starts up:

`WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 126: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

core-2023.3.6

### Device / Model

Topaz-2.9

### Diagnostics information

[config_entry-nest_protect-6cf22faced7363c55b1b7a4bdad5fed9.json.txt](https://github.com/iMicknl/ha-nest-protect/files/11129182/config_entry-nest_protect-6cf22faced7363c55b1b7a4bdad5fed9.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>
`WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 126: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by iMicknl** [comment]
@janusn to double check, do you use the cookie method version? (not in this repo).

**Comment by janusn** [comment]
> @janusn to double check, do you use the cookie method version? (not in this repo).

yes, the cookie method detailed at [https://github.com/chrisjshull/homebridge-nest](https://github.com/chrisjshull/homebridge-nest)

**Comment by Cruguah** [comment]
This issue is solved in commit [e7ac358](https://github.com/iMicknl/ha-nest-protect/pull/167/commits/e7ac358663ffeb05baf2df766b8515857f1427a0)

Please reinstall the integration using hacs

**Comment by janusn** [comment]
> This issue is solved in commit [e7ac358](https://github.com/iMicknl/ha-nest-protect/pull/167/commits/e7ac358663ffeb05baf2df766b8515857f1427a0)
> 
> Please reinstall the integration using hacs

Does reinstall mean clicking Redownload from the hamburger menu?
<img width="491" alt="Screen Shot 2023-04-25 at 9 54 16 pm" src="https://user-images.githubusercontent.com/21253783/234402145-34ed61ba-936e-44ad-9d4b-f4107bb6b657.png">


I have redownloaded and restarted the container afterwards. However, the warning was still logged as the last line below.

```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1053
User GID:    65548
───────────────────────────────────────

[custom-init] No custom files found, skipping...
2023-04-25 21:50:10.446 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-25 21:50:10.450 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-25 21:50:10.452 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-25 21:50:10.453 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
[ls.io-init] done.
2023-04-25 21:50:36.071 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2023-04-25 21:50:36.077 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2023-04-25 21:50:36.078 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2023-04-25 21:50:45.635 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 126: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

**Comment by Cruguah** [comment]
Yep, you have to use redownload from the hamburger menu and then you would get:
![image](https://user-images.githubusercontent.com/14362766/234516958-26aab5c6-2dc6-4eb2-8fa0-72f1228e5707.png)
This version doesn't show the message about async_setup_platforms. (At least not on my environment)

**Comment by iMicknl** [comment]
Please update to 0.4.0b1 via HACS or GitHub releases.

**Comment by iMicknl** [comment]
That is actually out of my reach. You probably added another GitHub repo to HACS, of a fork that uses the same name. The easy way is to remove the custom URL or ask the fork to rename the integration.

**Comment by janusn** [comment]
> That is actually out of my reach. You probably added another GitHub repo to HACS, of a fork that uses the same name. The easy way is to remove the custom URL or ask the fork to rename the integration.

That was what I thought at first. However, I discovered both repository were created by you though.
[https://ha.chubbie.duckdns.org/hacs/repository/448323715](https://ha.chubbie.duckdns.org/hacs/repository/448323715)
[https://ha.chubbie.duckdns.org/hacs/repository/562770573](https://ha.chubbie.duckdns.org/hacs/repository/562770573)

As I noticed from another repository [AitorDB/home-assistant-sun-card](https://github.com/AitorDB/home-assistant-sun-card), It is marked as archived. I don't know whether it helps but at least HA prompts me to remove it.
<img width="500" alt="Screen Shot 2023-04-26 at 2 28 45 pm" src="https://user-images.githubusercontent.com/21253783/234590578-60a1088e-572c-4202-9bb7-2fb61f1c2ee5.png">

**Comment by janusn** [comment]
I have just learned that I can manage custom repositories from the hamburger menu of HACS.

I have fixed the multiple repository problem. Sorry for bugging you.

**Comment by wafliron** [comment]
Confirming that after upgrading to 0.4.0b1 my Nest Protects have continued to work fine in HA and the async_setup_platforms warning is gone. Thanks for your work on this @iMicknl and @Cruguah.
