### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by deralte99** [iMicknl/ha-nest-protect#210]
### The problem

Upgraded today to 2023.2.5, the following error was thrown:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 4:02:53 PM (1 occurrences)
Last logged: 4:02:53 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nest_protect using this method at custom_components/nest_protect/__init__.py, line 126: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

2023.2.5

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.2.5",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Vancouver",
    "os_name": "Linux",
    "os_version": "5.15.79+truenas",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "nest_protect": {
      "version": "0.4.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "config_flow": true,
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "codeowners": [
      "@imicknl"
    ],
    "iot_class": "cloud_polling",
    "version": "0.4.0",
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "app_launch": {
      "updated_buckets": [
        {
          "object_key": "where.6680db70-2042-11e6-a772-22000b0d059d",
          "object_revision": -1068,
          "object_timestamp": 1565664897399,
          "value": {
            "wheres": [
              {
                "where_id": "00000000-0000-0000-0000-000100000000",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000001",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000002",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000003",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000004",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000005",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000006",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000007",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000009",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000e",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000f",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000010",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000011",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000012",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000013",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000014",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000015",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000017",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000018",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001d",
                "name": "**REDACTED**"
              }
            ]
          }
        },
        {
          "object_key": "topaz.18B430000039507E",
          "object_revision": 10373,
          "object_timestamp": 1681512617289,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-00010000000f",
            "creation_time": 1492880114000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.86.134",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A0",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "9509C5FC65C366DD",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1676834558,
            "home_away_input": false,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": false,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 32768,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1785369600,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1676834555,
            "component_pir_test_passed": true,
            "structure_id": "6680db70-2042-11e6-a772-22000b0d059d",
            "software_version": "3.5rc3",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1679274503,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1679274483,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 3,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-00010000000f",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 32768,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1469836800,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5261
          }
        },
        {
          "object_key": "structure.6680db70-2042-11e6-a772-22000b0d059d",
          "object_revision": -5101,
          "object_timestamp": 1681511041592,
          "value": {
            "swarm": [
              "topaz.18B430000039507E",
              "topaz.18B4300000394C3B",
              "topaz.18B43000003976FE"
            ],
            "last_action_by": "PHX",
            "manual_away_timestamp": 1676428101,
            "last_action": "RTS_SYNC",
            "emergency_contact_phone": "**REDACTED**",
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "city": "**REDACTED**",
            "name": "**REDACTED**",
            "eta_preconditioning_active": false,
            "creation_time": 1463938024105,
            "location": "**REDACTED**",
            "touched_by": {
              "touched_by": 1,
              "touched_id": "",
              "touched_user_id": "user.3551269"
            },
            "latitude": "**REDACTED**",
            "ifj_primary_fabric_id": "**REDACTED**",
            "state": "**REDACTED**",
            "away_timestamp": 1681511041,
            "structure_area": 213.6772,
            "topaz_hush_key": "**REDACTED**",
            "enable_goose": false,
            "away_setter": 1,
            "phone_hush_enable": true,
            "hvac_safety_shutoff_enabled": true,
            "house_type": "multi-family",
            "demand_charge_enabled": true,
            "rcs_sensor_swarm": [],
            "longitude": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "topaz_enhanced_auto_away_enabled": false,
            "address_lines": "**REDACTED**",
            "country_code": "CA",
            "hvac_smoke_safety_shutoff_enabled": true,
            "topaz_away": false,
            "tou_enabled": true,
            "renovation_date": "2010",
            "vacation_mode": false,
            "fabric_ids": [
              "9509C5FC65C366DD"
            ],
            "postal_code": "**REDACTED**",
            "emergency_contact_description": "**REDACTED**",
            "num_thermostats": "1",
            "entitlements": {},
            "dr_reminder_enabled": true,
            "members": [
              {
                "user": "**REDACTED**",
                "roles": [
                  "member"
                ]
              },
              {
                "user": "**REDACTED**",
                "roles": [
                  "owner"
                ]
              }
            ],
            "manual_eco_all": false,
            "emergency_contact_type": 1,
            "goose_sensor_events_enabled": true,
            "campaign_id": "bfda983c-5da4-437b-95c5-16207cc20cb1",
            "time_zone": "**REDACTED**",
            "user": "**REDACTED**",
            "clutches": [],
            "away": false,
            "devices": [],
            "tou_speedbump_count_remaining": 3
          }
        },
        {
          "object_key": "topaz.18B4300000394C3B",
          "object_revision": -26463,
          "object_timestamp": 1681514028570,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-000100000010",
            "creation_time": 1492880269000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.86.133",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A0",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "9509C5FC65C366DD",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1590695719,
            "home_away_input": false,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": false,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 32768,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1785369600,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1590695716,
            "component_pir_test_passed": true,
            "structure_id": "6680db70-2042-11e6-a772-22000b0d059d",
            "software_version": "3.5rc3",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1679274883,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1679274835,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 3,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-000100000010",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 32768,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1469836800,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5251
          }
        },
        {
          "object_key": "topaz.18B43000003976FE",
          "object_revision": 29192,
          "object_timestamp": 1681512940794,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-000100000006",
            "creation_time": 1492881419000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.86.135",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A0",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "9509C5FC65C366DD",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1676834562,
            "home_away_input": false,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": false,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 32768,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1785369600,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1676834559,
            "component_pir_test_passed": true,
            "structure_id": "6680db70-2042-11e6-a772-22000b0d059d",
            "software_version": "3.5rc3",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1679274512,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1679274463,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-000100000006",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 32768,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1469836800,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5260
          }
        }
      ],
      "service_urls": {
        "urls": {
          "rubyapi_url": "https://home.nest.com/",
          "czfe_url": "https://czfe21-front01-iad01.transport.home.nest.com",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "transport_url": "https://czfe21-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "direct_transport_url": "https://transport04-rts01-iad01.transport.home.nest.com:443"
        },
        "limits": {
          "thermostats_per_structure": 20,
          "structures": 5,
          "smoke_detectors_per_structure": 18,
          "smoke_detectors": 54,
          "thermostats": 60
        },
        "weave": {
          "service_config": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "access_token": "**REDACTED**"
        }
      },
      "weather_for_structures": {
        "structure.6680db70-2042-11e6-a772-22000b0d059d": {
          "current": {
            "icon": "partlycloudy",
            "temp_c": "**REDACTED**",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**"
          },
          "location": "**REDACTED**"
        }
      },
      "2fa_enabled": true
    }
  }
}

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Duplicate. Is already fixed in master and now also in the beta cookie branch.
