### ISSUE TITLE
Cookie Method No Longer Works?

### ISSUE THREAD

**Issue by deralte99** [iMicknl/ha-nest-protect#214]
### The problem

Ended up nuking my HA set up due to TrueCharts changes....long story.  Was trying to set up the Nest Protect integration again.  It no longer accepts the new Request Header under IssueToken.  Try it and it comes back as invalid.  I've killed the old tokens to start fresh, no change.  Did Google kill this or is it just me?

### What version of this integration (ha-nest-protect) has the issue?

0.3.11

### What version of Home Assistant Core has the issue?

2023.2.5

### Device / Model

Nest Protect Wired

### Diagnostics information

Can't even get that far.  It's a Google issue to authorize the access.

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by RedX8** [comment]
I've set it up today and it works.

**Comment by iMicknl** [comment]
Please update to latest pre-release (beta) via HACS or GitHub releases and try again.

**Comment by deralte99** [comment]
Still having issues.  Get the following from Google:

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure.
Follow the Out-of-Band (OOB) flow migration guide linked in the developer
docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

**Comment by iMicknl** [comment]
@deralte99 install the beta version.

**Comment by deralte99** [comment]
Fixed.  Thank you!  I think you mentioned going to the beta version in your
previous instructions.  I saw there was a HACS update and assumed that was
good enough.  Drilled in more to get on the proper beta channel and now is
good.  Now I have to go burn some toast!

**Comment by iMicknl** [comment]
Cool! @deralte99 since it is a beta version, all feedback (via a new GitHub issue) is welcome.
