### ISSUE TITLE
Translation Error when trying to sign in

### ISSUE THREAD

**Issue by BrandonG777** [iMicknl/ha-nest-protect#222]
### The problem

Using 4.0b1 loaded from HACS, I receive the following message where I normally should see a login page. I do see two fields that are unlabeled. I tried copying & pasting issue_token / cookies but no luck.

Translation Error: The intl string context variable "url" was not provided to the string "To link your Google account, [authorize your account](https://homeassistant.bahama.site/config/integrations).

After authorization, copy-paste the provided Auth Token code below."

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b1

### What version of Home Assistant Core has the issue?

2023.4.6

### Device / Model

Havent gotten this far

### Diagnostics information

cant get to this

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
What is your configured language in HA?

**Comment by twistedsanity** [comment]
I'm currently getting the same and my HA is configured to Country= United Kingdom, Language = English (GB)

**Comment by twistedsanity** [comment]
The work around for me was to switch the language to 'English', setup the plugin, then switch it back.

**Comment by BrandonG777** [comment]
Sorry, ended up migrating to HAOS last weekend and that resolved most of my issues including this one. Still very new to HA.

**Comment by JakeWharton** [comment]
Manually deleting the `pt-pt.json` file (as was done in c7210b80ccdfa16198e29509f55c4e4b6bf37ab1) will get rid of this error. That file contains translations of the 3.x strings and not the 4.x strings (which no longer contain a URL to click).

**Comment by iMicknl** [comment]
@JakeWharton thanks! In which version does this occur?

**Comment by JakeWharton** [comment]
In 4.0b1.

This is because the translations were updated in https://github.com/iMicknl/ha-nest-protect/commit/c7210b80ccdfa16198e29509f55c4e4b6bf37ab1 _after_ the 4.0b1 tag on the beta branch which also deletes the offending pt-pt.json file that breaks translation.

**Comment by iMicknl** [comment]
@JakeWharton oh, you are using the beta branch directly? Because this should not occur in the tagged version. I will clean up the beta branch and release 4.0b2 after this weekend. Feel free to do a PR as well.

**Comment by JakeWharton** [comment]
I installed the 4.0b1 tag from HACS which exhibits the problem. I performed the manual deletion of the file to unblock myself.

I'm not using the beta branch, just saying that the problem has already been fixed on the branch but after the latest available tag.

**Comment by kmjsmith** [comment]
have yo updated the package yet? becuase i still get this error while trying to install this.

**Comment by iMicknl** [comment]
@kmjsmith no sorry, not yet! If you take the main branch, it should work.

**Comment by iMicknl** [comment]
Should be fixed in latest beta! If you still see this issue, you might have a fork configured in HACS / something else is going wrong. Please remove your custom_components/nest_protect folder and install the new version manually.
