### ISSUE TITLE
Update the README.md on the code page to the newest version

### ISSUE THREAD

**Issue by janusn** [iMicknl/ha-nest-protect#223]
### Description

The description on the [landing page](https://github.com/iMicknl/ha-nest-protect) of this project has been outdated for a while. It is the primary reason a lot of people get lost on the Google authentication process (myself included), such as #105 shows.

Could @iMicknl update the landing page with the [latest version](https://github.com/iMicknl/ha-nest-protect/tree/v0.4.0b1)?

**Comment by iMicknl** [comment]
Fair point, @janusn. I will update the README refering to the latest beta release: https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b1. The reason the README does not provide the latest information around cookies, is because the cookie authentication is not in our main branch yet.

**Comment by hesspoint** [comment]
I just installed the latest Beta. When I try to re-authenticate it tells me 

Please get your issue_token and cookies following the instructions in the integration README and paste them below.

I understand that since it is beta, the readme is not updated yet. However I have no idea how to get this data. Are there any instructions you could post here how this works?

Thanks a ton :)

**Comment by iMicknl** [comment]
See https://github.com/iMicknl/ha-nest-protect/tree/beta#retrieving-issue_token-and-cookies, @hesspoint.

In a future release, there will be a link to this README. At the moment this prerelease is a community contribution, and I didn't had time yet to fully polish it.

**Comment by douginoz** [comment]
One small (show-stopper actually) problem.  The instructions to find the issue_token and cookies values are clear and work.  But there's nothing else describing what to do with these or where to put them.  
Installing Nest Protect via HACS installs v0.3.12, and after a restart of HA, when I go to 'Add Integration', I find 'Nest Protect', but it simply pops up a window asking for Account Type - Google Account or Google Account (Field Test).  Selecting either of them then prompts for an Access Token.  There's also a link to "Authorize your account" but that  returns the Error 400: invalid_request (Access Blocked: Nest's request is invalid).

So the instructions seem to be missing a key bit explaining how to get to the point of using the issue_token and cookies values.

**Comment by iMicknl** [comment]
Will be fixed when we move to a single version, hopefully in a few weeks.
