### ISSUE TITLE
Implement reauth flow when user is logged out

### ISSUE THREAD

**Issue by christensonautohome** [iMicknl/ha-nest-protect#229]
### Description

I'm using cookie method to access my nest protect.  Curious if there is a way to update the issue_token and cookie if it's ever lost connection.  Or is the only method an uninstall and reinstall of the add-on.

Seems like deleting and adding back the add-on is the only option.  if it is can an update be made to allow new issue_token and cookie to be updated?

thanks

**Comment by mcfarlde** [comment]
Where do I find this cookie beta?  My older v3.10 cookie installation just failed with recent HA update.  Reinstalling didn't help

**Comment by iMicknl** [comment]
@mcfarlde download here the beta from releases or from HACS. Make sure you didn’t configure any fork in HACS.

**Comment by mcfarlde** [comment]
Thanks!  Working again.

**Comment by christensonautohome** [comment]
@iMicknl curious why this was closed?  Is the enhancement added or did you complete because @mcfarlde's question was answered?  His question didn't seem to have anything to do with my enhancement request.

**Comment by iMicknl** [comment]
@christensonautohome thanks, I indeed closed it by mistake.

**Comment by rodalpho** [comment]
The integration just lost my cookie for some reason. Clicking on configuration asked me to input the token and cookie again, which worked fine. Pretty dang annoying of course, but that's Google's fault, not the integration's.

**Comment by iMicknl** [comment]
Tracked in #170
