### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by cantcodegood** [iMicknl/ha-nest-protect#236]
### The problem

Trying to install nest protect to my HA and receive an error when trying to authorize my google account prior to getting the access token.  When I click the 'authorize your account' link, I receive an error on Google's sign in page regarding an invalid request.

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.

Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.6.1

### Device / Model

Nest Protect (Wired)

### Diagnostics information

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

### Additional information

![Screenshot 2023-06-13 at 1 54 18 PM](https://github.com/iMicknl/ha-nest-protect/assets/36007553/caeee2b3-db2d-4aa8-8f60-54d8a33b99e8)
![Screenshot 2023-06-13 at 1 54 28 PM](https://github.com/iMicknl/ha-nest-protect/assets/36007553/e519d6ae-b8cc-40d0-91ee-b9f0c42d357e)

**Comment by iMicknl** [comment]
See #105 (pinned issue). You will need https://github.com/iMicknl/ha-nest-protect/tree/v0.4.0b1#nest-protect-integration-for-home-assistant (v0.4.0b1).
