### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by kmjsmith** [iMicknl/ha-nest-protect#238]
### The problem

hi when i go top authorize my nest account is it says invalid is thee a way to get my token another way? 

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

6.2

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by helifella** [comment]
I have the same issue.
<img width="344" alt="image" src="https://github.com/iMicknl/ha-nest-protect/assets/17753861/2c896156-b937-4bcb-b237-af32f78396b9">

**Comment by MAILPUB** [comment]
The beta version fixes this and works very well

**Comment by helifella** [comment]
Thanks

**Comment by papinist** [comment]
tried the beta version (4.0b2) but doesn't work for me.

**Comment by douginoz** [comment]
Make sure you have set a value for location in the nest app.  For me on my iPhone it’s located by using the gear icon top right, selecting the device in the “Protects” section, then in the next screen look under the “About” section for “Where”. The value there should be one of the room names you already use in HA, spelling identically and same case. I probably restarted HA a couple of times after that before I noticed that it started working. On Jun 30, 2023, at 03:57, Stefano ***@***.***> wrote:﻿
tried the beta version (4.0b2) but doesn't work for me.

**Comment by papinist** [comment]
Tried again this morning and new instructions appeared, on how to retrieve token and cookie, and it worked!
Thanks @douginoz for trying to help :)

**Comment by groutn1** [comment]
> Tried again this morning and new instructions appeared, on how to retrieve token and cookie, and it worked! Thanks @douginoz for trying to help :)
What did you end up doing to get it to work? I've done all the above plus ensuring my language is set to English and I still get the above error. Neither Beta version nor the latest release work.

**Comment by papinist** [comment]
There is a link that redirects here https://github.com/imicknl/ha-nest-protect/tree/beta#retrieving-issue_token-and-cookies
Following this instructions to retrieve token and cookies worked for me.

**Comment by nicholaswilde** [comment]
> There is a link that redirects here https://github.com/imicknl/ha-nest-protect/tree/beta#retrieving-issue_token-and-cookies Following this instructions to retrieve token and cookies worked for me.

This worked for me as well using [v0.4.0b2](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b2). The input fields weren't labelled for me. The top field was the token and the bottom field was the cookie. Also, I had to allow cookies in my settings for Incognito mode when following the linked instructions above.
