### ISSUE TITLE
KeyError: '00000000-0000-0000-917d-74187f6e457b' during setup using beta

### ISSUE THREAD

**Issue by douginoz** [iMicknl/ha-nest-protect#239]
### The problem

Installed the beta 0.4 version and obtained the issue_token/cookie values.  Entered them and was told it was successful, but there are no integration entities and no Nest Protect devices exist.   Enabling debug logging shows 

ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nest_protect platform for sensor
KeyError: '00000000-0000-0000-917d-74187f6e457b' 

and is repeated for binary_sensor, select, and switch.

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b1

### What version of Home Assistant Core has the issue?

2023.6.2

### Diagnostics information
```

```
### Home Assistant log

<details><summary>Logs</summary>

```
[home-assistant_nest_protect_2023-06-23T10-02-16.140Z.log](https://github.com/iMicknl/ha-nest-protect/files/11847295/home-assistant_nest_protect_2023-06-23T10-02-16.140Z.log)
[home-assistant_2023-06-23T09-54-57.413Z.log](https://github.com/iMicknl/ha-nest-protect/files/11847296/home-assistant_2023-06-23T09-54-57.413Z.log)
[config_entry-nest_protect-3d1e8dcfc301e7746636483ec0a5c015.json.txt](https://github.com/iMicknl/ha-nest-protect/files/11847297/config_entry-nest_protect-3d1e8dcfc301e7746636483ec0a5c015.json.txt)


```

</details>

### Additional information

I double-checked that the google account I'm using is associated with 2 Nest Protect devices, and the still-valid home.nest.com login shows the 2 devices:

- "Garage (Garage)":
Model	Topaz-2.7
Serial no.	06AA01AC151806XF
Software	3.5rc3
Battery life	OK
Replace by	12 Apr 2028
Last update	1 hr ago
Wi‑Fi MAC	18b430ae79b5
Wi‑Fi IP	192.168.1.161
802.15.4 MAC	18b4300000aa3a73

This "Garage" unit has 'Garage' as the "Where" (location) configured on the Nest webpage.
The second unit has 'Basement' as the location.

**Comment by iMicknl** [comment]
Did you change the locations recently?

**Comment by douginoz** [comment]
No.  Once I documented the errors and posted them I tried changing the Where field for the second unit on the nest website but it didn't affect anything.

And Since there's no devices found in HA there's no opportunity to change anything there.

**Comment by douginoz** [comment]
I changed the locations in the Nest app last night.  When I rebooted/updated HA to 6.3 I happened to check the logs and didn't see any errors for the nest protects.  Sure enough, they now appear correctly.  I don't have a clear correlation but perhaps having one of them with a blank location in the Nest app was the problem.
I'll leave it to someone to close this as the incident has disappeared, though the problem likely remains.

**Comment by dickd999** [comment]
I experience the same issue: configuration succeeded, and then no devices ("instellen mislukt") . I have 3 protect devices. 
The integration did work with the previous version ..

The log gives:
Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 09:59:08 (1 occurrences)
Last logged: 09:59:08

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by dickd999** [comment]
I did play around with the location of the devices after the error showed up an did some retries, samen (=no) result...

**Comment by iMicknl** [comment]
@dickd999 you have an unrelated issue. Make sure you run this version, and not a fork. In HACS remove the custom repository and install the latest beta version from this integration.

**Comment by amanbx** [comment]
I renamed a room in the Google home app and now my entire Protect integration is broken for all devices regardless of which room.


`
Logger: homeassistant.components.switch
Source: custom_components/nest_protect/entity.py:33
Integration: Switch (documentation, issues)
First occurred: 1:15:03 AM (75 occurrences)
Last logged: 8:00:06 PM

Error while setting up nest_protect platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nest_protect/switch.py", line 77, in async_setup_entry
    NestProtectSwitch(device, description, data.areas, data.client)
  File "/config/custom_components/nest_protect/entity.py", line 117, in __init__
    super().__init__(bucket, description, areas, client)
  File "/config/custom_components/nest_protect/entity.py", line 33, in __init__
    self.area = areas[self.bucket.value["where_id"]]
                ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '00000000-0000-0000-a978-xxxxxxxxxxz'

`

**Comment by DavidRSullivan** [comment]
In the duplicated closed issue, my details to the above issue are:

My auth started failing (similar failure to current issues), and my devices were listed as no longer reporting. I tried to fix the auth with no luck, I upgraded to the newest version, with no luck. Then I deleted the existing devices that were no longer being reported (because of the failed auth), uninstalled everything, rebooted, reinstalled, got auth to work, rebooted and that is what you see in the log.  No devices and the error reported here.

I will try changing locations as douginoz stated "I changed the locations in the Nest app last night. " and see if that results in anything different.

**Comment by DavidRSullivan** [comment]
No luck, tried everything I can think of, devices show absolute correct in both web app and IOS app, correct location, correct room.

Is there any way to turn on additional logging to see what information is received from nest itself?

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
