### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by nathangray** [iMicknl/ha-nest-protect#240]
### The problem

Following the installation instructions on github, using either of the blue My Add integration buttons gives an error:

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

This is probably a documentation issue.  It does work when I do it through HACS in HA.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.6.3

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

### Additional information

Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

**Comment by helifella** [comment]
I had the same issue. I installed it manually through HACS.

**Comment by iMicknl** [comment]
<img width="623" alt="image" src="https://github.com/iMicknl/ha-nest-protect/assets/1424596/acf01214-7cb5-49fd-803a-765159726f23">

How can I write it in a better way? It mentions that you first need to install the component (via HACS or manually), afterwards you can press the blue button.

**Comment by nathangray** [comment]
I think my issue is the position of the word "or", which suggests pressing the blue button is an alternative to "search, install, reboot, configure" rather than the intended "search, install, reboot" first, then either configure OR button

**Comment by iMicknl** [comment]
Thanks @nathangray! Feel free to do a PR by the way to change the wording.
