### ISSUE TITLE
No entities or Devices

### ISSUE THREAD

**Issue by mudparr** [iMicknl/ha-nest-protect#242]
### The problem

Already looked through past issues on this but nothing seems to work. I originally installed through HACS but the latest round (in troubleshooting) was a manual install of v0.4.0b2. Was able to do the cookie authentication just fine, but not matter how I tried, no devices or entities would show up. A download of the config_entry would show that all of the nest protect devices were found (can see all 9 devices and their settings), but the corresponding entries in HA are never created. The HA logs show errors around setting up the binary_sensors, sensors, select, and switch.

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b2

### What version of Home Assistant Core has the issue?

2023.6.3

### Diagnostics information

"installation_type": "Home Assistant OS",
    "version": "2023.6.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Denver",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.06.4",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>
[home-assistant_nest_protect_2023-07-04T04-24-18.582Z.log](https://github.com/iMicknl/ha-nest-protect/files/11944619/home-assistant_nest_protect_2023-07-04T04-24-18.582Z.log)

**Comment by jte71** [comment]
Same here @mudparr :(

**Comment by James-Heathcote** [comment]
how did you get this fixed, I am having the same problem
[home-assistant_nest_protect_2023-07-30T08-17-44.533Z.log](https://github.com/iMicknl/ha-nest-protect/files/12208749/home-assistant_nest_protect_2023-07-30T08-17-44.533Z.log)

**Comment by jte71** [comment]
On my first try I got the wrong **iframe** value.

**Comment by droolingtaz** [comment]
I am using 0.4b1 on HA 2023.8.1. I am having the same issue.  It appears I am getting past authentication, but the creation of the entities and devices is failing.

2023-08-10 22:46:50.210 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up nest_protect platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/nest_protect/binary_sensor.py", line 178, in async_setup_entry
NestProtectBinarySensor(
File "/config/custom_components/nest_protect/entity.py", line 118, in __init__
super().__init__(bucket, description, areas, client)
File "/config/custom_components/nest_protect/entity.py", line 33, in __init__
self.area = areas[self.bucket.value["where_id"]]
~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '00000000-0000-0000-a8af-988dd09e0ff3'

**Comment by iMicknl** [comment]
@mudparr please include your log.

@droolingtaz see https://github.com/iMicknl/ha-nest-protect/issues/239 for a possible solution.
