### ISSUE TITLE
Just thank you

### ISSUE THREAD

**Issue by JPFrancoia** [iMicknl/ha-nest-protect#246]
### Description

Just wanted to say thank you. This integration works like a charm. I had to install it manually (probably due to my custom HA install) and I had to follow the "hack-ish" procedure to get the token/cookies, but once done everything works.

Thank you for building this integration.

Feel free to close this issue

**Comment by iMicknl** [comment]
Thanks for sharing, @JPFrancoia! Happy to hear that it works :).
