### ISSUE TITLE
Google Account Authorisation Blocked

### ISSUE THREAD

**Issue by dan-cliff** [iMicknl/ha-nest-protect#255]
### The problem

Attempting to authorise my Google Account results in an Error 400: invalid_request.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.8.3

### Device / Model

Nest Protect Battery

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by Woodside22** [comment]
I have the same issue, the error seems to be OAuth versions - https://support.google.com/accounts/answer/12379384

**Comment by pauwer64** [comment]
I have same issue, error 400

**Comment by Lips2000** [comment]
Same issue here.

**Comment by nmcrae85** [comment]
same issue here

**Comment by thomas-tank** [comment]
I've also hit this problem on HA Core 2023.8.4

**Comment by iMicknl** [comment]
See #105. TLDR: use beta.

Will make the README more clear after my holidays.
