### ISSUE TITLE
asked to submit error to github by integration

### ISSUE THREAD

**Issue by Diddz7** [iMicknl/ha-nest-protect#257]
### The problem

unknown error occuring with the error asking the user to post the log as an issue on github

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b2

### What version of Home Assistant Core has the issue?

Frontend 20230705.1 - latest

### Device / Model

Topaz-2.7

### Home Assistant log

<details><summary>Logs</summary>
```
`This error originated from a custom integration.

Logger: custom_components.Nest_protect
Source: custom_components/Nest_protect/pynest/client.py:224
Integration: Nest_protect
First occurred: August 18, 2023 at 9:55:29 PM (41 occurrences)
Last logged: 4:57:59 PM

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/Nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/Nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.Nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
`
```

</details>

**Comment by korttoma** [comment]
I get the same errors on a daily basis, reloading the integration gets it back to running state.


This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:224
Integration: Nest Protect (documentation, issues)
First occurred: August 24, 2023 at 13:26:44 (52 occurrences)
Last logged: 07:26:55

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.







This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:222
Integration: Nest Protect (documentation, issues)
First occurred: August 24, 2023 at 13:26:44 (52 occurrences)
Last logged: 07:26:55

Could not interpret Nest response



This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:214
Integration: Nest Protect (documentation, issues)
First occurred: August 24, 2023 at 13:26:44 (52 occurrences)
Last logged: 07:26:55

Authentication error: invalid_request

**Comment by iMicknl** [comment]
Which version do you use of the component?

**Comment by Diddz7** [comment]
v0.4.0b2

**Comment by korttoma** [comment]
same here "v0.4.0b2"
Communication to the device seems to work even if I get the errors

**Comment by Diddz7** [comment]
> same here "v0.4.0b2" Communication to the device seems to work even if I get the errors

![image](https://github.com/iMicknl/ha-nest-protect/assets/140991292/e3c951c6-c97f-4432-a52d-d70cf5777106)

**Comment by korttoma** [comment]
@Diddz7 If it does not reconnect when you reload the integration you may have to generate new issueToken and cookie and configure the integration again.
