### ISSUE TITLE
Authorize Google account

### ISSUE THREAD

**Issue by jeffeck** [iMicknl/ha-nest-protect#260]
### The problem

After installing and adding as HACS integration, prompted to link Google account and provide the auth-token, however, the authorization results in: Error 400: invalid_request

Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.9.0

### Device / Model

Nest Protect (Battery)

### Diagnostics information

Access blocked: Nest’s request is invalid

You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by jmnovak50** [comment]
Same issue

**Comment by LudvigAstrom** [comment]
Same

**Comment by ajaymdesai** [comment]
Same issue

**Comment by Mickeyr61** [comment]
Fresh install same error

**Comment by nikotanghe** [comment]
Problem is due to the new oob flow that is now required to be implemented since jan 2023.

in short : 
google says : no more copy paste access tokens

more info : 

https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by iMicknl** [comment]
See #105, you need the beta version from this GitHub repo.

will make the instructions more clear after my holidays.

**Comment by swonge** [comment]
same issue

**Comment by iMicknl** [comment]
@swonge same reply... See #105. Please try to add a bit more meaningful comments or read at least the previous responses. Thanks!

**Comment by guybo-r** [comment]
> See #105, you need the beta version from this GitHub repo.
> 
> will make the instructions more clear after my holidays.

@iMicknl or anyone else.... Sorry for the newbie question, but HOW do i implement the beta release?  I'm not new to computers and programming (VB/VBA), but I am new to HA and Github
