### ISSUE TITLE
It would be fair to stop this integration as long as it is not working.

### ISSUE THREAD

**Issue by Matt2356a** [iMicknl/ha-nest-protect#261]
### The problem

Integration worked fine for over a year **but stopped recently.**
The new autorization (token, cookie) is not working -spend a couple of hours but finally deleted the integration. (see other issues regarding error 400)

I this it would be fair to set this integration to "defect" as long as there is not solution or a very detailed explanation. I followed the readme to get token and cookie via Chrome Dev Console after created the Google project and required authorization and the Nest project (including 5 USD payment). 

But all without success.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.9.2

### Device / Model

Nest protect (6 devices)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Many users have the beta version working, so without any logs / feedback, I don’t know what goes wrong. After my holidays, I will clarify in the README which version should be used (beta vs stable). You are not using the beta (pre release) version by the way, according to your version number mentioned.

The 5$ Nest project is not mentioned anywhere for this integration, so I am not sure where you got this information? 

I will close this issue. Feel free to create a new issue with your actual problem and log files.
