### ISSUE TITLE
Nest Protect Stopped working

### ISSUE THREAD

**Issue by akayami** [iMicknl/ha-nest-protect#264]
### The problem

Nest Protect Stopped working. All devices are not available after upgrading to the latest version of HA

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.8.4

### Device / Model

Multiple different nest protect versions

### Home Assistant log

<details><summary>Logs</summary>
```
2023-10-05 22:49:05.478 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

</details>

### Additional information

Using this image: 
ghcr.io/home-assistant/home-assistant:latest

I've also tried:
ghcr.io/home-assistant/home-assistant:beta

but it made no difference.

**Comment by mcfarlde** [comment]
For me too.

**Comment by iMicknl** [comment]
@akayami @mcfarlde how did you install this integration? I think you are using a fork (See "Custom Repositories" in HACS). Did you use the cookie method to set up the integration?

The latest version from this repository should not raise such errors.

**Comment by mcfarlde** [comment]
Yes, cookie method.  It has worked so long, I forgot.  Redoing it now.

**Comment by iMicknl** [comment]
If you use HACS, you need to remove the other repository from your custom repositories. Then reinstall the integration and use the latest beta (pre-release). Or manually install https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b1.

The cookie method is still not super stable unfortunately, but at least it is better than nothing.

**Comment by mcfarlde** [comment]
Does 2-step Verification break it?

**Comment by mcfarlde** [comment]
I turned oof 2-step verification, downloaded the latest cookie method custom component, made new Request url and cookies, tried the Google Account and the Filed Test and all fail.

Derek

**Comment by mcfarlde** [comment]
I notice the Request url doesn’t change

**Comment by iMicknl** [comment]
@mcfarlde what is the error you get now? If it is a different error than the startpost here, please create a new issue.

**Comment by akayami** [comment]
After following your instructions, I was able to fix my intergration.

1. I had to remove all existing setups.
2. Using HACS, find Nest Protect integration, and install it. Make sure to enable beta, and use latest tag. 
3. Follow the login instructions to get your `issue_token` and `cookies`. Make sure you just close the window when done (and not logged out). 
4. Fix everything else. 

I've used the latest beta version, namely `v0.4.0b2`

**Comment by boasist** [comment]
> After following your instructions, I was able to fix my intergration.
> 
> 1. I had to remove all existing setups.
> 2. Using HACS, find Nest Protect integration, and install it. Make sure to enable beta, and use latest tag.
> 3. Follow the login instructions to get your `issue_token` and `cookies`. Make sure you just close the window when done (and not logged out).
> 4. Fix everything else.
> 
> I've used the latest beta version, namely `v0.4.0b2`

This worked for me as well, copied the token and cookies and all synced right back up.
