### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by ethmik** [iMicknl/ha-nest-protect#268]
### The problem

I am attempting to install the integration.  I get the Nest Protect pop up and when I click the authorize your account link I am getting the error Access blocked: Nest’s request is invalid.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

23.10.5

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by IvesCoppens** [comment]
Same here, tried yesterday and same error code.

**Comment by iMicknl** [comment]
Duplicate of #105, please see the pinned issue.
