### ISSUE TITLE
Cookie method stops working

### ISSUE THREAD

**Issue by mschingel** [iMicknl/ha-nest-protect#287]
### The problem

Is there a certain way in 2023 to get the integration working without a new cookie every day?

I used chrome and just tried edge. Like others running Beta. After say 30 min to an hr later it will stop working. You can tell bc the calls for the switch entities fail. After a reboot you will see the red arrow indicating it cannot pass authentication. 

Some folks said they don’t have the issue, are they entering a new cooking every time. Do they have a special way to make there cookie last longer and not what I assume expires?

### What version of this integration (ha-nest-protect) has the issue?

Latest 

### What version of Home Assistant Core has the issue?

Latest 

### Device / Model

Battery Nest Protect

### Diagnostics information

Na

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

### Additional information

Na

**Comment by iMicknl** [comment]
Have you tried in incognito mode? I have done my first tests with the cookie auth myself last week, and it seems to run for a long time.

See https://github.com/iMicknl/ha-nest-protect/blob/702a631a5adb9a26c1ba43623ccfb2a7df04ca89/README.md#retrieving-issue_token-and-cookies for updated instructions we are working on.

**Comment by Pixel-Gavin** [comment]
I originally tried it in ingonito mode and within 6 hours I'd been kicked out.
I then did it, not in Incognito mode, using Edge instead - this one has been going two weeks now without issue. Not sure if Google has some kind of trigger with the login.

**Comment by mschingel** [comment]
I am trying in incognito mode now, I can confirm for my, edge and chrome in regular mode didnt last long.

So are you guys every time it expires re authorizing it?  I wanted if there was a way this could be automated somehow....

**Comment by Pixel-Gavin** [comment]
I think you'll struggle to automate it as that's kind of the point of the authorisation method.
I only had to do mine once and it's been completely reliable since.

**Comment by mschingel** [comment]
I wonder how your token can last longer while others do not.  I hope the
incognito mode for me in chrome works out.  Thanks for providing the
timeline, I'm hopeful...

**Comment by iMicknl** [comment]
@mschingel the original authentication method used a refresh token, and the refresh was done automatically. This is actually now blocked by Google, and no one has found a way to authenticate to the Nest servers anymore.

I am still on the old auth method, but am spending more time on the cookie auth now (that wasn't build by me originally) to make it more robust. This is the only method currently to authenticate at the moment.

**Comment by mschingel** [comment]
Thank you so much for the work and willingness to solve this :)

**Comment by BlackRockCity** [comment]
I also noted that it worked briefly and within hours stopped working. I assumed that I had done something incorrectly.

**Comment by mschingel** [comment]
@BlackRockCity 3 days ago, I used chrome and incognito mode to get the authentication.

so far it has lasted 3 days so far hopefully it last for much longer.
