### ISSUE TITLE
no longer getting screen for issue token and cookie is there a manual way to add this

### ISSUE THREAD

**Issue by thplex48178** [iMicknl/ha-nest-protect#294]
### The problem

I upgraded to 2023.12 docker from 2022.11 where I had nest protect working fine and I recall seeing the screen with the issue token an cookie,  but now I just get a single screen to add access toke, which immediately shows failed based on the instructions.  So has the configuration screen changed in this lates release ??

thanks

### What version of this integration (ha-nest-protect) has the issue?

latest

### What version of Home Assistant Core has the issue?

2023.12.4

### Device / Model

nest protect hardwire

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Which version of HA Nest Protect do you run? Please use the latest beta.

**Comment by thplex48178** [comment]
yeah, sorry, figured that out a lot later.  Can you update your instructions??  

thanks for making this work, love to use these motion detectors as an added bonus.

would be nice to get a way to enter/ recreate the the issue token setup as needed. thanks

**Comment by iMicknl** [comment]
>would be nice to get a way to enter/ recreate the the issue token setup as needed. thanks
What do you mean?

**Comment by thplex48178** [comment]
when you go reconfigure the service the screen to insert issue token and cookie is not showing.  The only way I know of fixing a failed instance of the integration is to delete it and recreate it.  So being able to re-initialize the communication with new token would be nice.  thanks

**Comment by iMicknl** [comment]
Thanks, that is a known bug indeed. Tracked via https://github.com/iMicknl/ha-nest-protect/issues/170.
