### ISSUE TITLE
TEMP_CELSIUS deprecation in HA core 2025.1

### ISSUE THREAD

**Issue by pvh0** [iMicknl/ha-nest-protect#303]
### The problem

WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues

### What version of this integration (ha-nest-protect) has the issue?

Current

### What version of Home Assistant Core has the issue?

2024.1

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
Duplicate of #290
