### ISSUE TITLE
connects OK but does not find any sensors

### ISSUE THREAD

**Issue by oscarhemberg** [iMicknl/ha-nest-protect#304]
### The problem

Hi,
I have installed through HACS and followed the instructions and everything seems to work fine. No error messages or similar during installation or setup or later.  Only problem is that none of my 8 Nest Protect units shows up. But I see them find in the Nest app or web interface. 

I have removed and reinstalled a few times and get the same result every time.

I wonder if this is because I have two homes in Nest and the other home has no Nest Protects, only cameras. And I can not find a way to choose default home or similar and I get no choice of home during installation so I wonder if the current integration supports multipole homes or if that could be the root cause?

Any help much appreciated

Oscar

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b4

### What version of Home Assistant Core has the issue?

2024.1.5

### Device / Model

Nest Protect 2nd Gen (Battery)

### Home Assistant log

<details><summary>Logs</summary>

[home-assistant_nest_protect_2024-01-21T14-51-38.788Z.log](https://github.com/iMicknl/ha-nest-protect/files/14001716/home-assistant_nest_protect_2024-01-21T14-51-38.788Z.log)
[config_entry-nest_protect-37a618344601ae00ae872e9fb85642e3.json.txt](https://github.com/iMicknl/ha-nest-protect/files/14001717/config_entry-nest_protect-37a618344601ae00ae872e9fb85642e3.json.txt)

</details>

**Comment by iMicknl** [comment]
Your issue is related to #239. I will see if I can fix this soon.

```
    self.area = areas[self.bucket.value["where_id"]]
                ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '00000000-0000-0000-acd4-efdb56eef958'
```

**Comment by jamesmny** [comment]
Seems like i am having the same situation whereby the install goes well, but i can not find any sensors.   Running the latest beta.   Any help greatly appreciated.   
The key error im getting is : KeyError: '3f2f64f5-0916-4e65-b7d0-21bb9b38f298'

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
