### ISSUE TITLE
Connection Drops-Out Almost Immediately

### ISSUE THREAD

**Issue by JohnMcIl** [iMicknl/ha-nest-protect#306]
### The problem

Within a short span of hours (less than 24), after successfully connecting to Nest Protect using the Cookies method, the connection fails.

Re-authenticating using the original method described in the latest beta release successfully reconnects, however, then drops out again.

![Screenshot 2024-01-26 at 9 21 45 am](https://github.com/iMicknl/ha-nest-protect/assets/3096550/066145d2-53ef-480a-bf5b-81eaf057ed0a)
![Screenshot 2024-01-26 at 9 21 43 am](https://github.com/iMicknl/ha-nest-protect/assets/3096550/656996d2-358a-4693-a544-119a139f4116)

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

2024.1.5

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
This is the biggest downside of the cookie method, and one of the reasons why it isn't part yet of the official integration. How did you generate the cookies? It seems your cookie is only valid for a short time / the session is killed very fast.

**Comment by JohnMcIl** [comment]
Thanks for your help Mick!

It was generated using your 'inspect' method.

Best wishes,





John McIlveen

**Comment by iotola** [comment]
I have a similar problem the connection lasts about 24 hours after which presence sensing no longer works, a restart of HA gets it working again. (I don't have to get another cookie.)

**Comment by iotola** [comment]
I just reloaded your integration, which resolves the problem with the presence detection. So a short-term fix might be to reload your integration every 24 hours. Not sure how to do that yet ...

**Comment by JohnMcIl** [comment]
Thank you Mick.

I am still seeing the 'failed to load integration' error on the Devices section of HA.

Best wishes,





John McIlveen

**Comment by Frazou1** [comment]
I have the same problem

**Comment by JohnMcIl** [comment]
Does anyone have any advice please?

Best wishes,





John McIlveen

**Comment by ajaymdesai** [comment]
Yep same issue for me too.

**Comment by JohnMcIl** [comment]
@iMicknl how are we travelling with this?
Is there currently ANY integration method for HA?
I would really like to get these two smoke alarms working…they are f*ing expensive and have smart functionality.
Hope you can help! Let me know if you hve a Patreon and I can support you somehow if you get this running 🙏

**Comment by iMicknl** [comment]
@JohnMcIl my time is quite limited at the moment and it's a pity that the original method of this integration is not functional for new users... I am still on the old auth method and this works like a charm.

However; recently I took some time to look into this and it did work for me longer than 24 hours. Are you sure your cookies are retrieved in the right way?

**Comment by JohnMcIl** [comment]
Thanks Mick!

I did this again to see if it would fix it.

I think maybe Incognito blocking third party cookies might have been the problem? Perhaps this needs to be bold in the instructions and also a URL to Google instructions?

Regardless, here is what I did :)
https://www.loom.com/share/6e7ec867a1b149e9b8cb5fd4adf49770

I’ll report back in a few days to let you know how it went!

Thanks again for your support.

Best wishes,





John McIlveen

**Comment by JohnMcIl** [comment]
Solved the problem! I think incognito was the issue.

Thanks again!!! 🙏🙏🙏

I’ll donate to your patreon if you have one.

Best wishes,





John McIlveen

**Comment by iMicknl** [comment]
@JohnMcIl apologies, I missed your reply. Would be good to update to the latest beta, where it should be more clear if you need to reauthenticate. Regarding donations, there is a 'sponsor' button on this repo. 😉

**Comment by JohnMcIl** [comment]
I have got it going now! Hasn’;t dropped for ages. It think it was an incognito issue upon setup/

Best wishes,





John McIlveen
