### ISSUE TITLE
The method for providing platform translations has changed in Home Assistant Core

### ISSUE THREAD

**Issue by emontnemery** [iMicknl/ha-nest-protect#314]
### Description

The method for providing platform translations has changed in Home Assistant Core, and this integration needs to be updated.

Details can be found in https://developers.home-assistant.io/blog/2024/03/05/platform_entity_translations_deprecation

**Comment by iMicknl** [comment]
Thanks! Fixed in latest beta, working on releasing it as a stable in the coming weeks.
