### ISSUE TITLE
Occupancy sensor missing

### ISSUE THREAD

**Issue by hesspoint** [iMicknl/ha-nest-protect#317]
### The problem

I noticed that in the screenshot in the readme it shows occupancy status. I know that the nest protect have one built in but for me I don't see the sensor in my devices

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

2024.3.1

### Device / Model

Nest Protect Battery powered

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
> This integration will add the most important sensors of your Nest Protect device (CO, heat and smoke) and the occupancy if your device is wired (to main power). In addition, it will expose several diagnostic and configuration entities. All sensor values will be updated real-time.

See documentation. Occupancy sensor is not supported for battery devices.
