### ISSUE TITLE
Cannot Authenticate

### ISSUE THREAD

**Issue by SwedenGuy** [iMicknl/ha-nest-protect#322]
### The problem
I installed the production version and experienced the authentication problems stated in [bug report 105](https://github.com/iMicknl/ha-nest-protect/issues/105). Reading deeper, it seems that the current recommendation is to install the latest beta, which I did. However I get a different authentication problem with the beta version.

After installing and restarting, am getting the following error when I try to set it up 

Translation Error: The intl string context variable "url" was not provided to the string "To link your Google account, [authorize your account](http://homeassistant.local:8123/config/integrations/dashboard).

<img width="596" alt="image" src="https://github.com/iMicknl/ha-nest-protect/assets/18058589/b61f5b0b-34e1-4f7f-bfdc-76f7a2a00113">

### What version of this integration (ha-nest-protect) has the issue?

 v0.4.0b4

### What version of Home Assistant Core has the issue?

2024.4.2

### Device / Model

_Cannot get that far_

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by bmos** [comment]
Are you sure you're using the beta version?
It seems like the url parameter is only part of that form on the main branch not the beta branch.

**Comment by jsnyder** [comment]
I currently see the same thing.  I cloned the repo, checked out the beta branch and copied the directory over to custom_components, restarted home assistant and got something like above.  This was after initially trying a non-beta automatically installed through HACS (which I'd since removed).

**Comment by cannondale0815** [comment]
Had the same "translation error" after upgrading from 3.x to the latest 4.x beta. I had to completely remove the integration and reinstall the beta to fix this.
