### ISSUE TITLE
Nest remote temperature sensor is sent at widely varying intervals

### ISSUE THREAD

**Issue by puterboy** [iMicknl/ha-nest-protect#323]
### The problem

Sometimes a new temperature reading from the Nest Remote sensor is sent every few minutes, sometimes every few hours.
Given that the temperature reading is in tenths of a degree, it is hard to imagine that my old, poorly insulated house stays at a constant temperature within a tenth of a degree for hours.

What governs the frequency at which temperature is polled and how can it be set to insure a reading occurs at least at a certain frequency.

### What version of this integration (ha-nest-protect) has the issue?

2.7

### What version of Home Assistant Core has the issue?

1.34.0

### Device / Model

Nest Remote Temperature Sensor

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
Too be honest, I wouldn't know. I don't own the temperature sensors myself. We subscribe to new events and Nest decides when to sent them, we don't have any influence on the polling interval.

**Comment by puterboy** [comment]
I think this is OK.
It seems to only send a value when the temperature has changed...
