### ISSUE TITLE
Deprecation Warnings for `StrEnum` from HA Core 2024.50b0

### ISSUE THREAD

**Issue by Anto79-ops** [iMicknl/ha-nest-protect#327]
### The problem

hello

just wanted to report a warning I received when updating to HA Core 2024.5.0b0 thanks

```
Logger: homeassistant.backports.enum
Source: helpers/deprecation.py:206
First occurred: 2:16:42 PM (1 occurrences)
Last logged: 2:16:42 PM

StrEnum was used from nest_protect, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'nest_protect' custom integration
```

### What version of this integration (ha-nest-protect) has the issue?

v0.3.12

### What version of Home Assistant Core has the issue?

 2024.5.0b0

### Device / Model

Nest Protect Battery

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
Fixed in [v0.4.0b5](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b5)
