### ISSUE TITLE
Deprecation warning for TEMP_CELCIUS constant in v0.4.0b4

### ISSUE THREAD

**Issue by stormshaker** [iMicknl/ha-nest-protect#328]
### The problem

Logger: homeassistant.const
Source: helpers/deprecation.py:206
First occurred: 10:41:34 AM (1 occurrences)
Last logged: 10:41:34 AM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

core-2024.4.4

### Device / Model

Topaz-2.33 and Topaz-2.34

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by AnthonyBe** [comment]
Already noted here in December 2023 - https://github.com/iMicknl/ha-nest-protect/issues/290
