### ISSUE TITLE
TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by grouts112** [iMicknl/ha-nest-protect#335]
### The problem

Getting the following error in Syslog:

WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

2024.6.1

### Device / Model

Nest Protect (wired)

### Diagnostics information

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1
Use UnitOfTemperature.CELSIUS instead,

### Home Assistant log

<details><summary>Logs</summary>

```
Jun 11 11:47:07 ha2 homeassistant[692]: #033[33m2024-06-11 11:47:07.553 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration#033[0m
```
</details>

**Comment by iMicknl** [comment]
Fixed in [v0.4.0b5](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b5)
