### ISSUE TITLE
Problem with "TEMP_CELSIUS"

### ISSUE THREAD

**Issue by styphonthal** [iMicknl/ha-nest-protect#337]
### The problem

On boot up/restart, I get this error: 2024-06-16 10:30:48.243 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b4

### What version of Home Assistant Core has the issue?

2024.6.2

### Device / Model

topaz 2.7

### Diagnostics information

as above. 

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by iMicknl** [comment]
Please update to the latest version ([v0.4.0b5](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b5)).
