### ISSUE TITLE
Deprecated constant noted in logs

### ISSUE THREAD

**Issue by arrikhan** [iMicknl/ha-nest-protect#339]
### The problem

As per logs ..

Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 9:50:43 AM (1 occurrences)
Last logged: 9:50:43 AM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

Core-2024.6.3

### Device / Model

Nest Detect Battery (2) Topaz-2.7

### Home Assistant log

<details><summary>Logs</summary>

```
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 9:50:43 AM (1 occurrences)
Last logged: 9:50:43 AM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nest_protect' custom integration ```
</details>


### Additional information

_No response_

**Comment by bmos** [comment]
Fixed in https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b5
