### ISSUE TITLE
Unknown pynest exception

### ISSUE THREAD

**Issue by BrianTomlinson** [iMicknl/ha-nest-protect#343]
### The problem

Errors in the log file

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b1

### What version of Home Assistant Core has the issue?

2024.7

### Device / Model

Nest protect battery and wired

### Home Assistant log

<details><summary>Logs</summary>

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:163
integration: Nest Protect (documentation, issues)
First occurred: 9 July 2024 at 23:50:29 (2 occurrences)
Last logged: 9 July 2024 at 23:50:29

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
```
</details>

**Comment by martymart8864** [comment]
Having the same issue here with 0.4.0b5 but was having the issue with 0.4.0b1.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 8:32:36 AM (2 occurrences)
Last logged: 8:37:36 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by chrisdfw** [comment]
Same

File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by DanDixon** [comment]
I am also getting this same issue with 0.4.0b5

**Comment by georgestoica93** [comment]
Same here. attached logs.
Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0
Nest Protect (HACS) v0.4.0b7
[Unknown pynest exception.txt](https://github.com/user-attachments/files/17661744/Unknown.pynest.exception.txt)

**Comment by GSzabados** [comment]
@iMicknl, could this be fixed somehow? Yesterday I managed to trigger one of the smoke detectors and I noticed later, that it has not reached HA at all. Basically this error makes the integration to stop working, I have it every 5 minutes.

**Comment by GSzabados** [comment]
@iMicknl, no worries. I know how it is working regarding side projects. 

My comments was really about the 5 minutes pauses. Before the last set of beta versions if an exception occurred, the integration stopped for a minute. This 5 minute stop just rendered it useless.

I will have a look at the debug log and get back on the other ticket what is happening with the `buckets`, and why isn't there any `object_key`.
