### ISSUE TITLE
Unable to send to google to log in

### ISSUE THREAD

**Issue by gerkintrigg** [iMicknl/ha-nest-protect#344]
### The problem

When I click to “authorize your account”, it just said:
Access blocked: Nest’s request is invalid
You can’t sign in because Nest sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Nest, see [error details](https://accounts.google.com/).
Error 400: invalid_request

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.7.4

### Device / Model

N/A

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by lee-booy** [comment]
Just trying this now and same issue for me, first time install

**Comment by kurtguy** [comment]
I get the same "Access blocked: Nest’s request is invalid" error when clicking authorize your account.

**Comment by araemo** [comment]
Error details:
>Error 400: invalid_request
>The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration >guide linked in the developer docs below to migrate your app to an alternative method.
>Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob flowName=GeneralOAuthFlow 

[Developer docs](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) that it links to.

**Comment by lee-booy** [comment]
Just looping back, this is a known issue it's actually in the release notes but not in the readme so didn't see it before. To get it working you need to switch to the beta release channel and follow the instructions.

https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.3.12

**Comment by iMicknl** [comment]
See #105 (pinned issue). TLDR: use the beta :)
