### ISSUE TITLE
pynest exception

### ISSUE THREAD

**Issue by Zaleo80** [iMicknl/ha-nest-protect#345]
### The problem

![image](https://github.com/user-attachments/assets/454bc2b7-8b69-4eb8-9eee-b1e5d6f85e1a)

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.7.3

### Device / Model

Battery

### Diagnostics information

I have no real issues, just found the error in the logging with the question to report it on GitHub, here it is.

### Home Assistant log

<details><summary>Logs</summary>

```
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>

### Additional information

Not sure if this is related, but after making a backup I get the message there is an error. Then in the logging I stumbled onto this message.
Following the onscreen instruction I created this bug report.

**Comment by iSteve-O** [comment]
I came to report this same issue.

**Comment by bpanucci** [comment]
I observed the same error message. Would be nice to know if it is something serious, because I have some smoke detectors running. They should work in case of fire.

**Comment by iMicknl** [comment]
@bpanucci your smoke detectors will still work, however if there is an issue between the communication of Nest server and this integration, you might not be notified via Home Assistant. But to reassure you, the normal Nest Protect functionality will never be impacted by any 3rd party integration.
