### ISSUE TITLE
Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by bmf7777** [iMicknl/ha-nest-protect#348]
### The problem

today i was asked to re-auth to generator a new token but received the error message in title. any ideas how to work around or a bug fix ? thanks, 

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

core-2024.7.4

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by existentialgolem** [comment]
Same issue here

**Comment by bretw444** [comment]
This was also reported 2 years ago and is still an open issue. I'm not sure this is still being supported?

**Comment by Thaboman1** [comment]
I have the same issue

**Comment by iMicknl** [comment]
See #105. TLDR: download latest beta / pre-release of this integration. Hopefully in the coming months we can fix some of the bugs and merge it back to the stable release..
