### ISSUE TITLE
Login to Google Loop

### ISSUE THREAD

**Issue by clefus** [iMicknl/ha-nest-protect#353]
### The problem

When trying to add the integration; Step 5 in the instructions, the sign in is successful, but then it immediately takes you back to the sign in with google page.  Doing multiple times does not make a difference.  It is a loop.  Is there a work around for this problem?

### What version of this integration (ha-nest-protect) has the issue?

new install

### What version of Home Assistant Core has the issue?

2024.8.3

### Device / Model

Next Protect Battery

### Diagnostics information

I can't get it installed.  Do not believe I can do this.

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by tech2urdoor** [comment]
+1

**Comment by iMicknl** [comment]
Most likely duplicate of #105. TLDR: use latest beta version

**Comment by idroyIT** [comment]
@iMicknl i don't think it is the same issue. It just brings you back to this screen after logging in:
![image](https://github.com/user-attachments/assets/888403f0-3844-4f48-bfd0-320d6fed3d21)
and these errors are in the console:
![image](https://github.com/user-attachments/assets/e4c14d50-300e-454a-a8db-51710b49e10c)
Not sure if it has something to do with it.

**Comment by clefus** [comment]
@iMicknl +1 to @idroyIT.  This does not appear to be the same issue to me.  We are not making it that far.  I had the next to latest beta version - so I did update to the latest beta version; but that is not the issue.  We are stuck in a login loop and do not make it to a point where we can pull the token.

**Comment by iMicknl** [comment]
Ah, you are facing the login loop on the regular Nest website? Do you have 3rd party cookies enabled?

**Comment by iMicknl** [comment]
@clefus good one! I thought it was already part of the docs. If someone wants to do a PR to the beta branch to improve the instructions, all contributions are welcome :).

**Comment by clefus** [comment]
@iMicknl - happy to do so.  Forgive a n00b ? - PR = "Pull Request" at the top of the page?  Just create a New Pull Request with the suggestion and language?  Let me know and I will do so.

I can wait a bit for @idroyIT.  But, I think this issue can be closed (looks like I can do so - but will wait for your reply and maybe for his).

**Comment by iMicknl** [comment]
Yes! You can also create pull request via the browser, by changing the README https://github.com/iMicknl/ha-nest-protect/edit/beta/README.md. Just make sure you target the 'beta' branch in your end.

**Comment by clefus** [comment]
Tried to do so; it failed - said I must be a collaborator.  I tried to improve it and even add screenshots....is there something else I need to do?

Thanks again for all of your help.

**Comment by idroyIT** [comment]
3rd party cookies did the trick, i also missed that one! :) Thnx for the help!

**Comment by clefus** [comment]
Since I could not do the pull request - Below were my proposed revisions - not sure if screenshots will carry over.  Closing this issue.

Current instructions:

Open a Chrome/Edge browser tab in Incognito Mode (or clear your cookies).
Open Developer Tools (View/Developer/Developer Tools).
Click on Network tab. Make sure 'Preserve Log' is checked.
In the Filter box, enter issueToken
Go to home.nest.com, and click Sign in with Google. Log into your account.
One network call (beginning with iframerpc) will appear in the Dev Tools window. Click on it.
In the Headers tab, under General, copy the entire Request URL (beginning with https://accounts.google.com/). This is your 'issue_token' in the configuration form.
In the Filter box, enter oauth2/iframe.
Several network calls will appear in the Dev Tools window. Click on the last iframe call.
In the Headers tab, under Request Headers, copy the entire cookie (include the whole string which is several lines long and has many field/value pairs - do not include the cookie: name). This is your 'cookies' in the configuration form.
Do not log out of home.nest.com, as this will invalidate your credentials. Just close the browser tab.

Proposed Revision:

1. Open a Chrome/Edge browser tab in Incognito Mode.
2. At the bottom of the browser window, disable "Block third-party cookies".

![image](https://github.com/user-attachments/assets/383408ab-91b6-47cd-b6c8-80c30389db05)


3. Open Developer Tools (View/Developer/Developer Tools or F12).
4. Click the Network tab.
5. Tick/check "Preserve Log".
6. In the Filter box, enter "issueToken".

![image](https://github.com/user-attachments/assets/48015f16-7942-4f16-beb1-b05f2e0d1109)


7. Go to home.nest.com, and click Sign in with Google. Log into your account.
8. One network call (beginning with "iframerpc") will appear in the Dev Tools window. Click on it.
9. In the Headers tab, under General, copy the entire Request URL (beginning with https://accounts.google.com/). This is your "issue_token" in the configuration form.
10. In the Filter box, enter "oauth2/iframe".
11. Several network calls will appear in the Dev Tools window. Click on the last "iframe" call.
12. In the Headers tab, under Request Headers, copy the entire cookie (include the whole string which is several lines long and has many field/value pairs - do not include the cookie: name). This is your 'cookies' in the configuration form.
13. Do not log out of home.nest.com, as this will invalidate your credentials. Just close the browser tab.
