### ISSUE TITLE
High bandwidth usage on v0.4.0b6

### ISSUE THREAD

**Issue by stevehop** [iMicknl/ha-nest-protect#363]
### The problem

After upgrading from v0.4.0b5 to v0.4.0b6 I noticed a significant increase in bandwidth usage of my HA instance which I've tracked down this integration. I've upgraded and downgraded a couple of times now to recreate the issue and each time my HA bandwidth usage goes from negligible to nearly 100Kb/s both up and down. The usage correlates with an increase in WAN usage so suggests the integration is communicating more with the cloud.

Areas highlighted on this bandwidth monitor graph are the times when running v0.4.0b6, the gaps are after reverting to v0.4.0b5 which is the expected usage.
![homeassistant](https://github.com/user-attachments/assets/4d79a6ab-5c77-4136-bdcc-ac9343e8f716)

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b6

### What version of Home Assistant Core has the issue?

2024.9.3

### Device / Model

Topaz-2.9 Nest Protect Wired
Topaz-2.7 Nest Protect Wired

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by stevehop** [comment]
Debug log:
[home-assistant_nest_protect_2024-10-02T08-56-56.982Z.log](https://github.com/user-attachments/files/17227362/home-assistant_nest_protect_2024-10-02T08-56-56.982Z.log)

**Comment by iMicknl** [comment]
Thanks @stevehop. I have noticed the same and will revert the latest contribution, since it is hammering the Nest Protect servers.
