### ISSUE TITLE
'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'

### ISSUE THREAD

**Issue by nikkehsolaris** [iMicknl/ha-nest-protect#369]
### The problem

On configuring the integration with a Google account I get this;

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 8:26:23 PM (3 occurrences)
Last logged: 8:26:32 PM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

### What version of this integration (ha-nest-protect) has the issue?

0.4.0

### What version of Home Assistant Core has the issue?

2024.10.2

### Home Assistant log

<details><summary>Logs</summary>

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 8:26:23 PM (4 occurrences)
Last logged: 8:31:43 PM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?
```
</details>

**Comment by iMicknl** [comment]
This code is not present in the latest versions (e.g. [v0.4.0b7](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b7)). Please update to the latest version.

**Comment by carldunham** [comment]
Still seeing this in the latest version (0.4.0).

**Comment by nikkehsolaris** [comment]
@iMicknl Can confirm what Carl is saying, I'm also seeing this in 0.4.0. Also tried deleting and resetting up config; got same error.

**Comment by iMicknl** [comment]
How did you install the integration? This code is not present in 0.4.0, you can check yourselves in https://github.com/iMicknl/ha-nest-protect/blob/main/custom_components/nest_protect/__init__.py.

Best is to remove the ha_nest_protect folder from your custom components folder manually and reinstall the integration. It seems you are still running an older version...

**Comment by nikkehsolaris** [comment]
> How did you install the integration? This code is not present in 0.4.0, you can check yourselves in https://github.com/iMicknl/ha-nest-protect/blob/main/custom_components/nest_protect/__init__.py.
> 
> Best is to remove the ha_nest_protect folder from your custom components folder manually and reinstall the integration. It seems you are still running an older version...

Yea very odd. I had even done a HACS redownload prior to retrying. Just removed & rebooted & reinstalled via HACS and it's working!

**Comment by carldunham** [comment]
> Still seeing this in the latest version (0.4.0).

Sorry, I realized that I was using a fork which still linked here. I removed that, added your latest release, and all works great. Thanks for your work, @iMicknl!
