### ISSUE TITLE
Sign-in loop when trying to sign-in to home.nest.com with incognito browser

### ISSUE THREAD

**Issue by JonboyP** [iMicknl/ha-nest-protect#376]
### The problem

AFter opening a new Chrome window in incognito mode and navigating to home.nest.com and clicking on "Sign in the Google" I sign in, I get taken through the usual Google 2FA, my credentials are accepted, and then I am presented again with login screen. I cannot get past this, it just loops.

Using a non-incognito mode browser I am able to follow the procedure and extract the cookie and request URL using developer mode.

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b1

### What version of Home Assistant Core has the issue?

2024.11.3

### Device / Model

Nest Protect wired

### Diagnostics information

There is no diagnostic information available since this is to do with integration set-up.

### Home Assistant log

No log available, I didn't get that far.

**Comment by iMicknl** [comment]
Did you turn 3rd party cookies on?

**Comment by JonboyP** [comment]
I did nothing except open a new incognito browser window and type in the URL. The written instructions make no mention of turning on cookies. When the webpage loaded I was not prompted to accept cookies.

**Comment by iMicknl** [comment]
Due to recent changes, we might need to add this to the README indeed. Can you allow third-party cookies in your browser settings?

**Comment by JonboyP** [comment]
In all honesty becaise everything is working properly (even though I deviated from the instructuons) I am reluctant to mess about with it now.

**Comment by xCHRIZZLEx** [comment]
@iMicknl - Confirming enabling Third Party Cookies in incognito mode resolves this issue (It appears to be off by default)

**Comment by JonboyP** [comment]
> Due to recent changes, we might need to add this to the README indeed. Can you allow third-party cookies in your browser settings?

Hi, since I had to re-start home assistant the Integration reports USER_LOGGED_OUT so I have been through the setup again, this time with 3rd party cookies enabled in a Chrome incognito window, and yes, as @xCHRIZZLEx has reported the sign-in loop is now gone. So it seems to me the readme just needs to be altered to tell users to enable 3rd party cookies in incognito mode.

Thank you.

**Comment by iMicknl** [comment]
Added to docs.
