### ISSUE TITLE
Problems with work around when authenticating Can't find devices to link to

### ISSUE THREAD

**Issue by oraclek76** [iMicknl/ha-nest-protect#379]
### The problem

I downloaded Release v0.4.0b7 and followed the steps to edit the redirect to be 
```
offline&prompt=consent&ack_oob_shutdown=2022-10-03
```
and I had to do that in incognito mode.  Once I did that I did get the google login but then it gave me the same error that the official login does. 
```
Can't find devices to link to haconnect
If your home has multiple members, the person who first set up the home must migrate their Nest Account to a Google Account before you can link to haconnect
```
Using the OS version of Home assistant on a PC.  
Core
2024.12.1
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.6
Maybe I need to use a specific version of the github repository?
I have two Nest Topaz-2.7 models.  Not sure they are supported by the integration or not.  Although HA does alert me that it finds a Nest product.  

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b7

### What version of Home Assistant Core has the issue?

2024.12.1

### Device / Model

Topaz-2.7

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by mazdarx2001** [comment]
in the incognito window, make sure the setting is "allow 3rd party cookies"

**Comment by oraclek76** [comment]
Some how I missed those instructions.  That worked once I figured out I missed that section.  Thanks for the help!
