### ISSUE TITLE
Throwin pynest exception error

### ISSUE THREAD

**Issue by perjury** [iMicknl/ha-nest-protect#38]
### The problem

I'm seeing errors logged on an hourly basis:
I don't know which device is causing it - I have 6 the same.

### What version of this integration (ha-nest-protect) has the issue?

0.3.0

### What version of Home Assistant Core has the issue?

core-2022.3.3

### Device / Model

Topaz-2.7

### Diagnostics information

[nest_protect-8e4132b1bc464e9959d3b69a916230d3-Nest Protect (First Floor)-4917fe9e152d5cfe79497dc9545c1538.json.txt](https://github.com/iMicknl/ha-nest-protect/files/8234622/nest_protect-8e4132b1bc464e9959d3b69a916230d3-Nest.Protect.First.Floor.-4917fe9e152d5cfe79497dc9545c1538.json.txt)

### Home Assistant log

<details><summary>Logs</summary>

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:229
Integration: Nest Protect (documentation, issues)
First occurred: 12:56:13 (5 occurrences)
Last logged: 17:40:29

Subscriber: pynest exception.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 225, in subscribe_for_data
    result = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe98-front01-iad01.transport.home.nest.com/v6/subscribe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 123, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 229, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

</details>

### Additional information

I've uploaded the diagnostics from the device which is showing a low battery in case that's the one throwing the errors

**Comment by iMicknl** [comment]
Thanks for reporting, this is an error on the service side, but we need better retry / backoff logic for this. 

I will close this, since we will track this in https://github.com/iMicknl/ha-nest-protect/issues/34. :)
