### ISSUE TITLE
Configuring integration via Google fails

### ISSUE THREAD

**Issue by jvrossum** [iMicknl/ha-nest-protect#384]
### The problem

When trying to obtain the Nest Protect access token, the google login page shows that the request has been blocked. 

The error that I get:

Fout 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Details van verzoek: redirect_uri=urn:ietf:wg:oauth:2.0:oob flowName=GeneralOAuthFlow

https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2024.12.5

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks (`)
```
</details>

**Comment by GSzabados** [comment]
Please try the Beta version, and read the instructions there.

**Comment by GSzabados** [comment]
Otherwise, please see this issue as reference: https://github.com/iMicknl/ha-nest-protect/issues/371
