### ISSUE TITLE
Make replace by sensor a valid timestamp.

### ISSUE THREAD

**Issue by jazzyisj** [iMicknl/ha-nest-protect#58]
### Description

The replace by sensors don't include a time which means HA doesn't see it as a valid timestamp.

![image](https://user-images.githubusercontent.com/44064559/158424821-13831bcc-a49e-48c7-b723-1cedf2f429f6.png)

This means we can't use the timestamp formatting options in the HA front end for entities.  In a case like this a relative time display is more intuitive than just displaying the date.   

```
- entity: sensor.nest_protect_upstairs_replace_by
  format: relative
```
![image](https://user-images.githubusercontent.com/44064559/158428803-b691d92e-1cc2-48fd-a12e-1163ec9526cb.png)

### Device (optional)

All

### Additional information

I've solved the issue in the meantime with a template sensor, but it would be nice if it came right out of the box with a valid timestamp.
```
    - name: 'Nest Replace'
      unique_id: nest_replace
      icon: mdi:calendar-account-outline
      device_class: timestamp
      state: "{{ states('sensor.nest_protect_upstairs_replace_by')|as_datetime|as_local }}"
```
![image](https://user-images.githubusercontent.com/44064559/158428149-8ce5662c-e277-4de8-a5ff-b4a81e82be9a.png)

**Comment by iMicknl** [comment]
Thanks for reporting! I don't understand why a sensor with device class `date` does not support the relative display option.

It seems that this will work when we use timestamp as the device class and add the timezone information.

**Comment by jazzyisj** [comment]
The date option shown on that page will display as a valid timestamp as a date only (rather than datetime). 
I agree, it would be nice if dates could also have a relative display option.

**Comment by iMicknl** [comment]
@jazzyisj could you create an issue on the front-end repository to track this? I think it would be great to have relative support for `date` sensors as well! For now I won't fix this in this integration, but perhaps we can add a small note to the README with your template sensor code?

**Comment by jazzyisj** [comment]
I think this may more a candidate for a feature request on the forum than an issue on the frontend git.  I don't believe there is any such animal as a date device_class.  Only timestamp.  Any time I've seen it come up the answer was convert it to a timestamp.  This integration is actually the first time I've come across any sensor sensor reporting a date instead of a full timestamp in a while.

A note in the README for those who would like to take advantage of the relative format feature for this sensor in the UI would be peachy though!

**Comment by iMicknl** [comment]
@jazzyisj date is a valid device class; according to the [developer documentation](https://www.home-assistant.io/integrations/sensor/#device-class). Other integrations use this as well to show a string that is a date string, and not a datetime string.

Thus a front-end feature request would be fine probably.

**Comment by jazzyisj** [comment]
https://community.home-assistant.io/t/date-device-class-relative-display/412469

**Comment by jazzyisj** [comment]
> date is a valid device class

I was referring to being valid device class for display formatting in the UI.  
Anyway, I've made the request.  Don't forget to vote for it! lol.
