### ISSUE TITLE
Support FieldTest Environment

### ISSUE THREAD

**Issue by SeraphimSerapis** [iMicknl/ha-nest-protect#65]
### Description

Nest uses a Field Test environment that is served by different endpoints.

It would be fantastic if this integration would allow to select the field test environment in addition to the (default) prod environment.

[homebridge-nest](https://github.com/chrisjshull/homebridge-nest) is doing a great job managing the [endpoints](https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-endpoints.js) and [authentication](https://github.com/chrisjshull/homebridge-nest/blob/master/login.js).

Happy to help testing or provide more information if useful!

**Comment by iMicknl** [comment]
@SeraphimSerapis thanks for your feature request! What would be a reason to have a Field Test environment as a choice?

I indeed saw this feature in HomeBridge, however I didn't understand the need. :-)

**Comment by SeraphimSerapis** [comment]
@iMicknl I appreciate your swift response. This environment is where Nest/Google employees and a sizeable group of external testers evaluate new features/actively reports issues with new app versions/... before they become available GA.

**Comment by iMicknl** [comment]
Makes sense, it should be a relatively small change indeed. I am just thinking how to reflect this in the Home Assistant interface. Just a dropdown during initial configuration, where you can select 'Production' vs 'Field Test' environment sounds the best to me currently.

If this was just for Google employees, adding it to the Configuration Flow wouldn't make a lot of sense, but it makes sense if groups of external users are using this as well.

**Comment by iMicknl** [comment]
@SeraphimSerapis could you give https://github.com/iMicknl/ha-nest-protect/archive/refs/heads/enhancement/support_field_test_env.zip a try? Extract this file and place `custom_components/nest_protect` in your `custom_components` folder.

**Comment by SeraphimSerapis** [comment]
Done! I got this:
```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:189
Integration: Nest Protect (documentation, issues)
First occurred: 20:15:04 (1 occurrences)
Last logged: 20:15:04

__init__() got an unexpected keyword argument 'error'
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 87, in async_step_account_link
    refresh_token = await self.async_validate_input(user_input)
  File "/config/custom_components/nest_protect/config_flow.py", line 45, in async_validate_input
    await client.authenticate(
  File "/config/custom_components/nest_protect/pynest/client.py", line 189, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: __init__() got an unexpected keyword argument 'error'

```

**Comment by SeraphimSerapis** [comment]
I tried fixing it by changing the following in `pynest/const.py`: 
```
NEST_ENVIRONMENTS: dict[str, NestEnvironment] = {
    "production": NestEnvironment(
        name="Google Account",
        client_id="733249279899-1gpkq9duqmdp55a7e5lft1pr2smumdla.apps.googleusercontent.com",  # Nest iOS application
        host="home.nest.com", # Regular Nest host
    ),
    "fieldtest": NestEnvironment(
        name="Google Account (Field Test)",
        client_id="384529615266-57v6vaptkmhm64n9hn5dcmkr4at14p8j.apps.googleusercontent.com",  # Test Flight Beta Nest iOS application
        host="home.ft.nest.com", # Nest FT host
    ),
}
```

And in `pynest/client.py` I replaced every occurrence of `home.nest.com` with `f"{self.environment.host}"`. Example:
````
async with self.session.get(
            f"https://{self.environment.host}/session",
            headers={
                "Authorization": f"Basic {nest_auth.jwt}",
                "cookie": "G_ENABLED_IDPS=google; eu_cookie_accepted=1; viewer-volume=0.5; cztoken="
                + nest_auth.jwt,
            },
        ) as ...
```

However, I now get the following error message, so I must have messed up somewhere:
<img width="593" alt="Screen Shot 2022-04-29 at 20 32 38" src="https://user-images.githubusercontent.com/160543/166004276-bed2482b-86cc-421a-9b4c-051f3648dffe.png">

The logs sadly don't help with additional details.

**Comment by iMicknl** [comment]
Thanks, I will have a look! I missed that another URL is required as well. :)

**Comment by iMicknl** [comment]
@SeraphimSerapis could you try another version of https://github.com/iMicknl/ha-nest-protect/archive/refs/heads/enhancement/support_field_test_env.zip? :)

**Comment by SeraphimSerapis** [comment]
Getting there! Entering the token works now, however devices are not retrieved. I get the following error:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/pynest/client.py:209
Integration: Nest Protect (documentation, issues)
First occurred: 22:43:28 (1 occurrences)
Last logged: 22:43:28

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 70, in async_setup_entry
    data = await client.get_first_data(nest.access_token, nest.userid)
  File "/config/custom_components/nest_protect/pynest/client.py", line 209, in get_first_data
    self.transport_url = result["service_urls"]["urls"]["transport_url"]
KeyError: 'service_urls'
```

**Comment by iMicknl** [comment]
Thanks! Can you perhaps share your diagnostics information? I am not sure which other differences there are between both environments, I would say that 'service_urls' are still present...

**Comment by SeraphimSerapis** [comment]
Ah, I believe I found the culprit: 
```
# App launch API endpoint
APP_LAUNCH_URL_FORMAT = "https://home.nest.com/api/0.1/user/{user_id}/app_launch"
```

This one would also need to change to `home.ft.nest.com`. So I changed it to `APP_LAUNCH_URL_FORMAT = "{host}/api/0.1/user/{user_id}/app_launch"` in `const.py` and applied this change to `client.py`:
```
async def get_first_data(self, nest_access_token: str, user_id: str) -> Any:
        """Get a Nest refresh token from an authorization code."""
        async with self.session.post(
            APP_LAUNCH_URL_FORMAT.format(host=self.environment.host, user_id=user_id),
            json=NEST_REQUEST,
            headers={
                "Authorization": f"Basic {nest_access_token}",
                "X-nl-user-id": user_id,
                "X-nl-protocol-version": str(1),
            },
        ) as response:
```

Applied these changes and things work great now! Thanks for making this happen!

**Comment by iMicknl** [comment]
Ah oops, I missed that one! Thanks, I will fix this and merge.

**Comment by iMicknl** [comment]
Thanks for the debug help and to get this feature in! Could you confirm that latest `main` works?

**Comment by SeraphimSerapis** [comment]
It seems like something in the config screen may have gotten lost in the merging process:
<img width="591" alt="Screen Shot 2022-04-30 at 07 31 29" src="https://user-images.githubusercontent.com/160543/166092777-1cdb84f5-5f3a-4a58-83be-0c00ec515f47.png">
<img width="398" alt="Screen Shot 2022-04-30 at 07 31 41" src="https://user-images.githubusercontent.com/160543/166092789-120bc5cc-7a2b-4624-bbe1-dff44979eaa7.png">

@iMicknl please let me know how I can best help. I'm happy to keep on testing!

**Comment by iMicknl** [comment]
@SeraphimSerapis to which language is your Home Assistant instance? I can not reproduce this behaviour. Can you double check if you replaced all files correctly? It seems that your translation folder didn't come through.

**Comment by SeraphimSerapis** [comment]
@iMicknl Not sure what happened. I deleted the whole folder, cloned your main branch and am using that version now successfully. This is good to go! Thanks again!
