### ISSUE TITLE
Duplicate Config options

### ISSUE THREAD

**Issue by simps100** [iMicknl/ha-nest-protect#72]
### The problem

Hi,

I just did an updated to 0.3.4 - all seems to be working but it looks like config items are all duplicated - one seems to show as a switch and appears to work, and the other shows as "Unavailable" - is is OK to go through removing the ones which are not working or is there a problem in my config?

Thanks
Marc

![nest1](https://user-images.githubusercontent.com/60661312/164802153-ced0f957-5dc8-438e-870b-e03253dbeb1d.PNG)
![nest2](https://user-images.githubusercontent.com/60661312/164802157-3341cf9b-01c6-4843-a3c8-46582947593f.PNG)
![nest3](https://user-images.githubusercontent.com/60661312/164802162-f3f10212-0f63-47c4-929a-4c7c80fcc113.PNG)

### What version of this integration (ha-nest-protect) has the issue?

0.3.4

### What version of Home Assistant Core has the issue?

core-2022.4.6

### Device / Model

Nest Protect - Wired

### Diagnostics information

[nest_protect-cc94591b3f656a4388e50823c1b41d6c-Nest Protect (Hallway)-efd05c0fce859dd3995745ff56220d45.json.txt](https://github.com/iMicknl/ha-nest-protect/files/8544357/nest_protect-cc94591b3f656a4388e50823c1b41d6c-Nest.Protect.Hallway.-efd05c0fce859dd3995745ff56220d45.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
This is indeed a breaking change. (See update change log). You can remove them or just remove and re add the integration config entry.
