### ISSUE TITLE
Authorization Error Error 400: invalid_request Required parameter is missing: response_type

### ISSUE THREAD

**Issue by arrikhan** [iMicknl/ha-nest-protect#84]
### The problem

Successfully installed Nest Protect in HACS, and then when attempting to install on config page, I am prompted for an authorisation key. 

On clicking authorise my account (assuming to get a key), I receive the following response.

```
Authorization Error
Error 400: invalid_request
Required parameter is missing: response_type
```

Have tried this on the last few iterations of Home Assistant (current is 2022.5.2)

### What version of this integration (ha-nest-protect) has the issue?

0.3.7

### What version of Home Assistant Core has the issue?

2022.5.2

### Device / Model

Nest Protect Battery

### Diagnostics information

Don’t get that far…

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Do you have a Google Account or do you try to login with a Nest Account?

**Comment by arrikhan** [comment]
Ive transferred to a google account long ago. I have nest thermostat working with another integration.

**Comment by iMicknl** [comment]
Can you add a screenshot of the error and where you get it? I will look into this, perhaps this is caused by a recent update.

Do I understand correctly that you face this error on the Google website?

**Comment by arrikhan** [comment]
I tried the same process on a laptop rather than an iPad. The process worked successfully. I am not sure why it did not succeed using chrome on an iPad.
