### ISSUE TITLE
The state of CO Status and Smoke status are not detected on Nest Smoke on battery

### ISSUE THREAD

**Issue by Lajull-fr** [iMicknl/ha-nest-protect#85]
### The problem

Tank you for your job !
![image](https://user-images.githubusercontent.com/85118947/167703144-fb0ecc54-2dfd-4e38-8c1f-d06e9b5046ae.png)
![image](https://user-images.githubusercontent.com/85118947/167703218-16d425a5-f888-4e9d-bb2a-ca3a42777ee2.png)
![image](https://user-images.githubusercontent.com/85118947/167703268-6c4d3e7b-bc69-4425-9692-5c3680ec8d6e.png)

### What version of this integration (ha-nest-protect) has the issue?

0.3.7

### What version of Home Assistant Core has the issue?

core-2022.5.3

### Device / Model

Nest Protect Battery

### Diagnostics information
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.5.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.15.0-27-generic",
    "supervisor": "2022.05.1",
    "host_os": "Ubuntu 22.04 LTS",
    "docker_version": "20.10.15",
    "chassis": "desktop",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.24.5",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "govee_ble_hci": {
      "version": "0.10.1",
      "requirements": [
        "bleson==0.1.8"
      ]
    },
    "webrtc": {
      "version": "v2.3.0",
      "requirements": []
    },
    "ble_monitor": {
      "version": "8.6.4",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.12",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.1.5",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "nest_protect": {
      "version": "0.3.7",
      "requirements": []
    },
    "myEnedis": {
      "version": "1.5.1",
      "requirements": [
        "packaging>=20.8"
      ]
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "config_flow": true,
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "codeowners": [
      "@imicknl"
    ],
    "iot_class": "cloud_polling",
    "version": "0.3.7",
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "device": {
      "controllable_name": "Battery",
      "firmware": "3.4rc6",
      "model": "Topaz-2.9"
    },
    "app_launch": {
      "updated_buckets": [
        {
          "object_key": "where.6b4213f4-d026-11ec-84e6-12a8ff611f1f",
          "object_revision": -6508,
          "object_timestamp": 1652162400151,
          "value": {
            "wheres": [
              {
                "where_id": "00000000-0000-0000-0000-00010000000c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000005",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000013",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000001",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000010",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000017",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000002",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000006",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000012",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000009",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000f",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000007",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000011",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000015",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000003",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000e",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000004",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000014",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000000",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000018",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001a",
                "name": "**REDACTED**"
              }
            ]
          }
        },
        {
          "object_key": "structure.6b4213f4-d026-11ec-84e6-12a8ff611f1f",
          "object_revision": -11280,
          "object_timestamp": 1652199557747,
          "value": {
            "swarm": [
              "topaz.18B43000418068FA"
            ],
            "manual_away_timestamp": 1652199553,
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "name": "**REDACTED**",
            "eta_preconditioning_active": false,
            "location": "**REDACTED**",
            "touched_by": {
              "touched_by": 0,
              "touched_id": "",
              "touched_user_id": ""
            },
            "latitude": "**REDACTED**",
            "ifj_primary_fabric_id": "**REDACTED**",
            "away_timestamp": 1652199556,
            "topaz_hush_key": "**REDACTED**",
            "enable_goose": false,
            "away_setter": 1,
            "phone_hush_enable": true,
            "hvac_safety_shutoff_enabled": true,
            "rcs_sensor_swarm": [],
            "longitude": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "topaz_enhanced_auto_away_enabled": false,
            "country_code": "FR",
            "hvac_smoke_safety_shutoff_enabled": false,
            "topaz_away": false,
            "vacation_mode": false,
            "fabric_ids": [
              "FBC77845CB8A0816"
            ],
            "postal_code": "**REDACTED**",
            "entitlements": {},
            "dr_reminder_enabled": true,
            "members": [
              {
                "user": "**REDACTED**",
                "roles": [
                  "owner"
                ]
              },
              {
                "user": "**REDACTED**",
                "roles": [
                  "member"
                ]
              }
            ],
            "manual_eco_all": false,
            "goose_sensor_events_enabled": false,
            "time_zone": "**REDACTED**",
            "user": "**REDACTED**",
            "clutches": [],
            "away": false,
            "devices": []
          }
        },
        {
          "object_key": "topaz.18B43000418068FA",
          "object_revision": -32046,
          "object_timestamp": 1652206355841,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-00010000000c",
            "creation_time": 1652162788774,
            "installed_locale": "fr_FR",
            "ntp_green_led_brightness": 1,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.1.28",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A1",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "FBC77845CB8A0816",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.9",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "home_away_input": true,
            "device_locale": "fr_FR",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 32768,
            "wired_or_battery": 1,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1918944000,
            "certification_body": 2,
            "component_pir_test_passed": true,
            "structure_id": "6b4213f4-d026-11ec-84e6-12a8ff611f1f",
            "software_version": "3.4rc6",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 2,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1652163684,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1652163633,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-00010000000c",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 32768,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": false,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1603411200,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5193
          }
        }
      ],
      "service_urls": {
        "urls": {
          "rubyapi_url": "https://home.nest.com/",
          "czfe_url": "https://czfe84-front01-iad01.transport.home.nest.com",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "transport_url": "https://czfe84-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "direct_transport_url": "https://transport04-rts09-iad01.transport.home.nest.com:443"
        },
        "limits": {
          "thermostats_per_structure": 20,
          "structures": 5,
          "smoke_detectors_per_structure": 18,
          "smoke_detectors": 54,
          "thermostats": 60
        },
        "weave": {
          "service_config": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "access_token": "**REDACTED**"
        }
      },
      "weather_for_structures": {
        "structure.6b4213f4-d026-11ec-84e6-12a8ff611f1f": {
          "current": {
            "icon": "sunny",
            "temp_c": "**REDACTED**",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**"
          },
          "location": "**REDACTED**"
        }
      },
      "2fa_enabled": true
    }
  }
}
### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

### Additional information

I'm in France

**Comment by iMicknl** [comment]
Do you currently have smoke and CO in your house? 🔥 

If not; I don't see the issue. 😉 Not detected means that there is no abnormal activity detected.

**Comment by Lajull-fr** [comment]
Ah ok, I thought the sensors were not detected ^^ 
My bad ^^ and sorry for the bad indentation.
Thanks for your quick return ;)
