### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by olafvs** [iMicknl/ha-nest-protect#87]
### The problem

After setting up in HACS I try to enter the token I got from google. But somehow it's not accepted. The token contains a '/' maybe it has someting to do with the problem...

I run docker with version 2022.4.7

### What version of this integration (ha-nest-protect) has the issue?

0.3.7

### What version of Home Assistant Core has the issue?

2022.4.7

### Home Assistant log

<details><summary>Logs</summary>

```
__init__() got an unexpected keyword argument 'error'
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 87, in async_step_account_link
    refresh_token = await self.async_validate_input(user_input)
  File "/config/custom_components/nest_protect/config_flow.py", line 45, in async_validate_input
    await client.authenticate(
  File "/config/custom_components/nest_protect/pynest/client.py", line 197, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: __init__() got an unexpected keyword argument 'error'
```

</details>

**Comment by iMicknl** [comment]
Thanks for reporting, @olafvs! We definitely need better error reporting there. 

I will add this, however I have some feeling that you don't have a Google account yet, could this be the case?

**Comment by olafvs** [comment]
I thought I already migrated, but I didn't. So I migrated just now, tried again, and now it works. Sorry for this.

Thanks for pointing this out.
