### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by DigiLive** [iMicknl/ha-nest-protect#90]
### Description

Just installed the integration on a dutch Home Assistant instance.
I've noticed the entities at sensors, configuration and diagnose sections are in English (E.g. Battery Health).

Do you care about getting them translated to dutch?

### Device (optional)

Nest Protect (Wired)

**Comment by iMicknl** [comment]
Thanks for your suggestion. Unfortunately Home Assistant doesn’t support translating the entity names, thus this cannot be translated.

Everything that can be translated, should be translated already. I’m Dutch as well :-).
