### ISSUE TITLE
Occupancy not shown?

### ISSUE THREAD

**Issue by vandenbogerd** [iMicknl/ha-nest-protect#91]
### The problem

In the screenshots of the add-on, we see occupancy, but in my installation (4 Nest Protects) it is not shown.

### What version of this integration (ha-nest-protect) has the issue?

0.3.7

### What version of Home Assistant Core has the issue?

core-2022.6.5

### Device / Model

Nest Protect (battery)

**Comment by iMicknl** [comment]
> This integration will add the most important sensors of your Nest Protect device (CO, heat and smoke) and the occupancy if your device is wired (to main power). 

Device limitation, as discussed in the README.
