### ISSUE TITLE
Cant activate the nest protect from the integration section

### ISSUE THREAD

**Issue by macnet1** [iMicknl/ha-nest-protect#93]
### The problem

I receive the following error when trying to loads the integration. 

_Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant._

Thanks in advance for your help

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.6.7

### Device / Model

Nest Smoke detector

### Diagnostics information

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
How did you install the integration? Can you check your logs?

**Comment by macnet1** [comment]
HI Mick, sure thing this is all I have in the logs:

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: July 4, 2022, 2:29:25 PM (1 occurrences)
Last logged: July 4, 2022, 2:29:25 PM

Error occurred loading configuration flow for integration nest_protect: No module named 'custom_components.nest_protect_old.pynest.const'

**Comment by wesselkranenborg** [comment]
I'm having the same issue. It's also not available from the 'Add integration' dialog or on the home assistant website.

My repro path is clicking this link: https://my.home-assistant.io/redirect/config_flow_start/?domain=nest_protect

Click on 'OPEN LINK'
![image](https://user-images.githubusercontent.com/4964604/177839117-89d823e2-e66f-4658-b590-9c7aaa950ba9.png)

Then the following error is shown:
![image](https://user-images.githubusercontent.com/4964604/177839431-c99741f1-3580-4d58-a073-fc41ed79c987.png)

I'm having the latest and greatest version of HA:
![image](https://user-images.githubusercontent.com/4964604/177839514-65d413f9-fc49-4a48-bb4f-659c2f399d05.png)

**Comment by iMicknl** [comment]
> Error occurred loading configuration flow for integration nest_protect: No module named 'custom_components.nest_protect_old.pynest.const'

@macnet1 did you rename the component? Why does it show 'nest_protect_old'?

@wesselkranenborg please include your log as well, otherwise I cannot debug this.

For both of you, if you are maybe not very familiar with custom components, you can also install this component via HACS.

**Comment by macnet1** [comment]
@iMicknl I renamed the folder as a result of the error message and tried to reinstall the component I don't understand why its picked up 'nest_protect_old'. I have now deleted that folder with still no change and in the logs I get -

Logger: homeassistant.config_entries
Source: config_entries.py:784
First occurred: 10:22:47 AM (1 occurrences)
Last logged: 10:22:47 AM

Error occurred loading configuration flow for integration nest_protect: No module named 'custom_components.nest_protect_old.pynest.const'

Is there a way to remove this error ?

Thanks :)

**Comment by nappyjim** [comment]
Hi all. I was gonna post I was having the same issue but then I had a "duh" moment.  Maybe its the same issue for you guys...

The Add integration button wont work until the you add the repository to HACS, then reboot, then click on the link again and it will work.  This was my issue.

So if you dont see this in your HACS INTEGRATIONS page, you will NEVER be able to use that link to add it to your HA INTEGRATIONS.

---To creator, you may want to add that in your instructions as I was confused at first too.  Just tell people they still need to download the repository first, then click the quick link.

![image](https://user-images.githubusercontent.com/71914301/177912227-a1f6ffbc-491d-4a28-8ab8-95a493b4701e.png)

**Comment by wesselkranenborg** [comment]
> Hi all. I was gonna post I was having the same issue but then I had a "duh" moment. Maybe its the same issue for you guys...
> 
> The Add integration button wont work until the you add the repository to HACS, then reboot, then click on the link again and it will work. This was my issue.
> 
> So if you dont see this in your HACS INTEGRATIONS page, you will NEVER be able to use that link to add it to your HA INTEGRATIONS.
> 
> ---To creator, you may want to add that in your instructions as I was confused at first too. Just tell people they still need to download the repository first, then click the quick link.
> 
> ![image](https://user-images.githubusercontent.com/71914301/177912227-a1f6ffbc-491d-4a28-8ab8-95a493b4701e.png)

This was indeed the issue at my side, so my bad. Sorry.

It would indeed be nice if that's added to the readme. For newbies like me, that would be helpful :-).

**Comment by iMicknl** [comment]
@wesselkranenborg @nappyjim not sure what I can add, any suggestions? Looking at the [README](https://github.com/iMicknl/ha-nest-protect#hacs) it already mentions that you need to install & reboot?

**Comment by nappyjim** [comment]
> @wesselkranenborg @nappyjim not sure what I can add, any suggestions? Looking at the [README](https://github.com/iMicknl/ha-nest-protect#hacs) it already mentions that you need to install & reboot?

Granted  both myself and @wesselkranenborg  should have read slower, but at quick glance I saw these directions as, "i can install this either manually or via Hacs.  If I want to do it through HACS, I just need to click the 'Add Integration' button and I should be done.

I would suggest splitting up the install into steps.  My eyes are drawn to numbered directions as opposed to one paragraph with multiple steps inside of it.   Great integration BTW!

Step 1:  Install the HAC integration.  List options for how to do this
Step 2: Reboot Home assistant
Step 3: Install home assistant integration.  List options for how do to this.


![image](https://user-images.githubusercontent.com/71914301/178088038-b01c3398-c026-401a-b408-757ccd111dbd.png)

**Comment by walterheck** [comment]
I experienced exactly the same and until searching for and reading this issue do I understand I should have RTFM'd a bit more carefully. Starting with home assistant you become used to seeing a "add integration" button and just clicking it, assuming all works from there :)
