### ISSUE TITLE
Replace by sensor (adjustable) date format

### ISSUE THREAD

**Issue by FoUStep** [iMicknl/ha-nest-protect#94]
### Description

The current date format is this
`2030-12-27T00:00:00`

Could you please make this in something more readable (and thus better scriptable) by removing the T00:00:00 as no time is available for the value "Replace By" the Nest Protect devices.

Would be nice to have an EU (or NL to me) date format or make it adjustable for the user: dd-mm-yyyy.

### Device (optional)

Both wired and wireless

### Additional information

<img width="955" alt="Screenshot 2022-07-20 at 22 20 40" src="https://user-images.githubusercontent.com/14996435/180074273-3beb9206-409e-47ea-9982-31b0374eeb5f.png">

**Comment by iMicknl** [comment]
Have a look at this similar issue: https://github.com/iMicknl/ha-nest-protect/issues/58#issuecomment-1068507456.

Currently it is a date object and you are able to use this within Home Assistant to do calculations and show it in a more human readable way.

**Comment by FoUStep** [comment]
Missed this since it was closed (only looked at open ones). Sorry.
