### ISSUE TITLE
Nest Sensors won't show up

### ISSUE THREAD

**Issue by vparfaniuc** [iMicknl/ha-nest-protect#95]
### The problem

For some reason the Nest Sensors linked to my thermostats won't show up with the Home Assistant. The seem to be working for a while but then they stopped working. 
I can access the Nest Protects in my house but not the sensors. Any idea how to get these working are highly appreciated. 
Thank you 

### What version of this integration (ha-nest-protect) has the issue?

v0.3.8

### What version of Home Assistant Core has the issue?

core-2022.7.6

**Comment by Anto79-ops** [comment]
I believe this integration is only for the NEST Protect.

You'll need to use HA Nest integration for your thermostat.

https://www.home-assistant.io/integrations/nest/

**Comment by Skates1616** [comment]
> I believe this integration is only for the NEST Protect.
> 
> You'll need to use HA Nest integration for your thermostat.
> 
> https://www.home-assistant.io/integrations/nest/

Sensors definitely work, just added an integration today and they populated.

**Comment by iMicknl** [comment]
@vparfaniuc please add your diagnostics information so I can investigate.
