### ISSUE TITLE
AdGaurd Home list - transport.home.nest.com

### ISSUE THREAD

**Issue by Anto79-ops** [iMicknl/ha-nest-protect#98]
### The problem

Hi!

Just curious about the nature of the transport URL

`transport.home.nest.com`

Its possible that my AdGaurd home with a certain list is blocking this url.

https://github.com/home-assistant/core/issues/75275

I simple do not use that list anymore and all is fine. I could report as a false positive to the "The Blocklist Project- Ad", and tell them to take it off the list, but before I do, just wanted to know what `transport.home.nest.com` is used for.

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.7.7 and 2202.8.0b1

### Device / Model

Nest Protect Battery

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Google Nest Protect still uses the `home.nest.com` API's for communication. We use this URL to listen for status updates.
